import type { OrderLifecycleStage } from "@/lib/orders/order-lifecycle-types";

/** High-level stage graph (FoodOps narrative). Not all hops are persisted independently in Prisma. */
const NEXT: Partial<Record<OrderLifecycleStage, OrderLifecycleStage[]>> = {
  DRAFT: ["REQUESTED", "CANCELLED"],
  REQUESTED: ["NEEDS_MAPPING", "NEEDS_CUSTOMER_INFO", "NEEDS_FULFILLMENT_INFO", "READY_FOR_PRODUCTION", "CONFIRMED", "CANCELLED"],
  NEEDS_MAPPING: ["READY_FOR_PRODUCTION", "REQUESTED", "CANCELLED"],
  NEEDS_CUSTOMER_INFO: ["REQUESTED", "READY_FOR_PRODUCTION", "CANCELLED"],
  NEEDS_FULFILLMENT_INFO: ["READY_FOR_PRODUCTION", "CANCELLED"],
  NEEDS_PAYMENT_REVIEW: ["READY_FOR_PRODUCTION", "COMPLETED", "CANCELLED"],
  READY_FOR_PRODUCTION: ["PRODUCTION_PLANNED", "IN_PRODUCTION", "CANCELLED"],
  PRODUCTION_PLANNED: ["IN_PRODUCTION", "CANCELLED"],
  IN_PRODUCTION: ["PRODUCTION_COMPLETE", "READY_FOR_PACKING", "PACKING", "CANCELLED"],
  PRODUCTION_COMPLETE: ["READY_FOR_PACKING", "PACKING", "CANCELLED"],
  READY_FOR_PACKING: ["PACKING", "CANCELLED"],
  PACKING: ["PACKED", "CANCELLED"],
  PACKED: ["READY_FOR_PICKUP", "OUT_FOR_DELIVERY", "CANCELLED"],
  READY_FOR_PICKUP: ["COMPLETED", "CANCELLED"],
  OUT_FOR_DELIVERY: ["COMPLETED", "CANCELLED"],
  CONFIRMED: ["READY_FOR_PRODUCTION", "IN_PRODUCTION", "CANCELLED"],
  ON_HOLD: ["REQUESTED", "CONFIRMED", "READY_FOR_PRODUCTION", "CANCELLED"],
  FAILED: ["NEEDS_REVIEW", "REQUESTED", "CANCELLED"],
  NEEDS_REVIEW: ["REQUESTED", "NEEDS_MAPPING", "CANCELLED"],
};

export function allowedLifecycleStageTargets(from: OrderLifecycleStage): OrderLifecycleStage[] {
  return NEXT[from] ?? [];
}
