import type {
  MenuTemplate,
  OnboardingMenuTemplateId,
  QuickStartRestaurantType,
} from "@/lib/onboarding/quick-start-types";
import { ONBOARDING_MENU_TEMPLATE_IDS } from "@/lib/onboarding/quick-start-types";

export const MENU_TEMPLATES: Record<OnboardingMenuTemplateId, MenuTemplate> = {
  full_service: {
    id: "full_service",
    title: "Full service restaurant",
    description: "Appetizers, mains, desserts, and drinks for dine-in.",
    businessType: "RESTAURANT",
    operatingModel: "WALK_IN_DAILY",
    menuTitle: "Dining room menu",
    categories: ["SNACKS", "MAINS", "DESSERTS", "BEVERAGES"],
    items: [
      { name: "Soup of the day", price: 9, category: "SNACKS", description: "Chef's daily soup." },
      { name: "Caesar salad", price: 12, category: "SNACKS" },
      { name: "Bruschetta", price: 10, category: "SNACKS" },
      { name: "Grilled chicken", price: 18, category: "MAINS" },
      { name: "Pasta Alfredo", price: 16, category: "MAINS" },
      { name: "Pan-seared salmon", price: 24, category: "MAINS" },
      { name: "Veggie risotto", price: 17, category: "MAINS" },
      { name: "Kids pasta", price: 10, category: "MAINS" },
      { name: "Tiramisu", price: 9, category: "DESSERTS" },
      { name: "Chocolate lava cake", price: 10, category: "DESSERTS" },
      { name: "House wine (glass)", price: 8, category: "BEVERAGES" },
      { name: "Craft beer", price: 7, category: "BEVERAGES" },
      { name: "Espresso", price: 4, category: "BEVERAGES" },
      { name: "Iced tea", price: 3, category: "BEVERAGES" },
      { name: "Chef's tasting plate", price: 32, category: "MAINS" },
    ],
  },
  qsr: {
    id: "qsr",
    title: "Quick service",
    description: "Burgers, sides, and combo-friendly items.",
    businessType: "CAFE",
    operatingModel: "WALK_IN_DAILY",
    menuTitle: "Counter menu",
    categories: ["MAINS", "SIDES", "BEVERAGES"],
    items: [
      { name: "Classic burger", price: 11.5, category: "MAINS" },
      { name: "Crispy chicken sandwich", price: 10.5, category: "MAINS" },
      { name: "Veggie wrap", price: 9.5, category: "MAINS" },
      { name: "Fries", price: 4, category: "SIDES" },
      { name: "Onion rings", price: 4.5, category: "SIDES" },
      { name: "Chicken nuggets (6)", price: 6, category: "SIDES" },
      { name: "Fountain drink", price: 2.5, category: "BEVERAGES" },
      { name: "Milkshake", price: 5.5, category: "BEVERAGES" },
      { name: "Combo meal", price: 14, category: "MAINS", description: "Burger, fries, drink." },
      { name: "Side salad", price: 5, category: "SIDES" },
    ],
  },
  bakery: {
    id: "bakery",
    title: "Bakery & pastry",
    description: "Bread, pastries, coffee, and sandwiches.",
    businessType: "BAKERY",
    operatingModel: "BAKERY_CUSTOM_PREORDERS",
    menuTitle: "Bakery case",
    categories: ["BAKERY", "BEVERAGES", "MAINS"],
    items: [
      { name: "Croissant", price: 4.5, category: "BAKERY" },
      { name: "Sourdough loaf", price: 7, category: "BAKERY" },
      { name: "Pain au chocolat", price: 4, category: "BAKERY" },
      { name: "Blueberry muffin", price: 3.5, category: "BAKERY" },
      { name: "Latte", price: 5, category: "BEVERAGES" },
      { name: "Cold brew", price: 4.5, category: "BEVERAGES" },
      { name: "Chocolate cake slice", price: 8, category: "BAKERY" },
      { name: "Ham & cheese sandwich", price: 11, category: "MAINS" },
      { name: "Quiche slice", price: 9, category: "MAINS" },
      { name: "Cookie (3-pack)", price: 6, category: "BAKERY" },
    ],
  },
  bar: {
    id: "bar",
    title: "Bar & lounge",
    description: "Cocktails, beer, wine, and bar snacks.",
    businessType: "BAR",
    operatingModel: "WALK_IN_DAILY",
    menuTitle: "Bar menu",
    categories: ["BAR", "SNACKS", "MAINS"],
    items: [
      { name: "House lager", price: 7, category: "BAR" },
      { name: "Margarita", price: 12, category: "BAR" },
      { name: "Old fashioned", price: 14, category: "BAR" },
      { name: "Aperol spritz", price: 11, category: "BAR" },
      { name: "Red wine (glass)", price: 10, category: "BAR" },
      { name: "Zero-proof spritz", price: 8, category: "BAR" },
      { name: "Nachos", price: 13, category: "SNACKS" },
      { name: "Wings (8)", price: 14, category: "SNACKS" },
      { name: "Sliders (3)", price: 15, category: "MAINS" },
      { name: "Charcuterie board", price: 22, category: "SNACKS" },
      { name: "Truffle fries", price: 11, category: "SNACKS" },
      { name: "Flatbread", price: 16, category: "MAINS" },
    ],
  },
  ghost_kitchen: {
    id: "ghost_kitchen",
    title: "Ghost kitchen",
    description: "Delivery-optimized bowls and sides.",
    businessType: "GHOST_KITCHEN",
    operatingModel: "SHOPIFY_WOO_MARKETPLACE",
    menuTitle: "Delivery menu",
    categories: ["MAINS", "SIDES", "BEVERAGES"],
    items: [
      { name: "Chicken bowl", price: 12, category: "MAINS" },
      { name: "Veggie bowl", price: 11, category: "MAINS" },
      { name: "Garlic noodles", price: 10, category: "MAINS" },
      { name: "Beef rice bowl", price: 13, category: "MAINS" },
      { name: "Side salad", price: 5, category: "SIDES" },
      { name: "Spring rolls (4)", price: 6, category: "SIDES" },
      { name: "Iced tea", price: 3, category: "BEVERAGES" },
      { name: "Bottled water", price: 2, category: "BEVERAGES" },
    ],
  },
  catering: {
    id: "catering",
    title: "Catering",
    description: "Packages and per-person mains.",
    businessType: "CATERING",
    operatingModel: "CATERING_QUOTES_EVENTS",
    menuTitle: "Catering packages",
    categories: ["MAINS", "SIDES", "DESSERTS", "SNACKS"],
    items: [
      { name: "Buffet package (per person)", price: 28, category: "MAINS" },
      { name: "Sandwich platter", price: 65, category: "MAINS" },
      { name: "Garden salad tray", price: 35, category: "SIDES" },
      { name: "Cookie dozen", price: 24, category: "DESSERTS" },
      { name: "Breakfast box (per person)", price: 16, category: "MAINS" },
      { name: "Fruit & cheese board", price: 48, category: "SNACKS" },
    ],
  },
  food_truck: {
    id: "food_truck",
    title: "Food truck",
    description: "Handheld tacos and quick bites.",
    businessType: "OTHER",
    operatingModel: "WALK_IN_DAILY",
    menuTitle: "Truck menu",
    categories: ["MAINS", "SIDES", "BEVERAGES", "DESSERTS"],
    items: [
      { name: "Street taco (2)", price: 8, category: "MAINS" },
      { name: "Loaded fries", price: 9, category: "SIDES" },
      { name: "Burrito bowl", price: 11, category: "MAINS" },
      { name: "Quesadilla", price: 9, category: "MAINS" },
      { name: "Churros", price: 5, category: "DESSERTS" },
      { name: "Agua fresca", price: 4, category: "BEVERAGES" },
      { name: "Lime soda", price: 3, category: "BEVERAGES" },
      { name: "Combo plate", price: 14, category: "MAINS" },
    ],
  },
  pizza: {
    id: "pizza",
    title: "Pizza",
    description: "Classic pies, slices, and sides.",
    businessType: "RESTAURANT",
    operatingModel: "WALK_IN_DAILY",
    menuTitle: "Pizza menu",
    categories: ["MAINS", "SIDES", "BEVERAGES"],
    items: [
      { name: "Margherita (12\")", price: 14, category: "MAINS" },
      { name: "Pepperoni (12\")", price: 16, category: "MAINS" },
      { name: "Veggie supreme (12\")", price: 17, category: "MAINS" },
      { name: "Meat lovers (12\")", price: 18, category: "MAINS" },
      { name: "Cheese slice", price: 4.5, category: "MAINS" },
      { name: "Garlic knots", price: 7, category: "SIDES" },
      { name: "Caesar side salad", price: 8, category: "SIDES" },
      { name: "Fountain soda", price: 2.5, category: "BEVERAGES" },
    ],
  },
  sushi: {
    id: "sushi",
    title: "Sushi & Japanese",
    description: "Rolls, nigiri, and appetizers.",
    businessType: "RESTAURANT",
    operatingModel: "WALK_IN_DAILY",
    menuTitle: "Sushi bar menu",
    categories: ["MAINS", "SNACKS", "BEVERAGES"],
    items: [
      { name: "California roll (8)", price: 9, category: "MAINS" },
      { name: "Spicy tuna roll (8)", price: 11, category: "MAINS" },
      { name: "Dragon roll (8)", price: 14, category: "MAINS" },
      { name: "Salmon nigiri (2)", price: 7, category: "MAINS" },
      { name: "Tuna nigiri (2)", price: 8, category: "MAINS" },
      { name: "Edamame", price: 5, category: "SNACKS" },
      { name: "Miso soup", price: 4, category: "SNACKS" },
      { name: "Gyoza (5)", price: 8, category: "SNACKS" },
      { name: "Sashimi combo", price: 22, category: "MAINS" },
      { name: "Poke bowl", price: 15, category: "MAINS" },
      { name: "Green tea", price: 3, category: "BEVERAGES" },
      { name: "Sake (glass)", price: 9, category: "BEVERAGES" },
    ],
  },
  coffee_shop: {
    id: "coffee_shop",
    title: "Coffee shop",
    description: "Espresso drinks, tea, and light bites.",
    businessType: "CAFE",
    operatingModel: "WALK_IN_DAILY",
    menuTitle: "Café menu",
    categories: ["BEVERAGES", "BAKERY", "MAINS"],
    items: [
      { name: "Espresso", price: 3.5, category: "BEVERAGES" },
      { name: "Cappuccino", price: 5, category: "BEVERAGES" },
      { name: "Latte", price: 5.5, category: "BEVERAGES" },
      { name: "Cold brew", price: 4.5, category: "BEVERAGES" },
      { name: "Matcha latte", price: 6, category: "BEVERAGES" },
      { name: "Chai latte", price: 5.5, category: "BEVERAGES" },
      { name: "Croissant", price: 4, category: "BAKERY" },
      { name: "Banana bread slice", price: 4.5, category: "BAKERY" },
      { name: "Avocado toast", price: 11, category: "MAINS" },
      { name: "Breakfast sandwich", price: 9, category: "MAINS" },
    ],
  },
};

export function getMenuTemplate(type: OnboardingMenuTemplateId): MenuTemplate {
  return MENU_TEMPLATES[type];
}

export function listMenuTemplates(): MenuTemplate[] {
  return ONBOARDING_MENU_TEMPLATE_IDS.map((id) => MENU_TEMPLATES[id]);
}

export function isQuickStartRestaurantType(
  id: OnboardingMenuTemplateId,
): id is QuickStartRestaurantType {
  return id !== "pizza" && id !== "sushi" && id !== "coffee_shop";
}
