/** Stripe Checkout uses smallest currency unit; these charge in whole units (no *100). */
export const STRIPE_ZERO_DECIMAL_CURRENCIES = new Set([
  "bif",
  "clp",
  "djf",
  "gnf",
  "jpy",
  "kmf",
  "krw",
  "mga",
  "pyg",
  "rwf",
  "ugx",
  "vnd",
  "vuv",
  "xaf",
  "xof",
  "xpf",
]);

/** Lowercase ISO 4217 codes Stripe commonly supports for card charges (subset; expand as needed). */
const STRIPE_CARD_CURRENCIES = new Set(
  [
    "usd",
    "aed",
    "afn",
    "all",
    "amd",
    "ang",
    "aoa",
    "ars",
    "aud",
    "awg",
    "azn",
    "bam",
    "bbd",
    "bdt",
    "bgn",
    "bif",
    "bmd",
    "bnd",
    "bob",
    "brl",
    "bsd",
    "bwp",
    "byn",
    "bzd",
    "cad",
    "cdf",
    "chf",
    "clp",
    "cny",
    "cop",
    "crc",
    "cve",
    "czk",
    "djf",
    "dkk",
    "dop",
    "dzd",
    "egp",
    "etb",
    "eur",
    "fjd",
    "fkp",
    "gbp",
    "gel",
    "gip",
    "gmd",
    "gnf",
    "gtq",
    "gyd",
    "hkd",
    "hnl",
    "hrk",
    "htg",
    "huf",
    "idr",
    "ils",
    "inr",
    "isk",
    "jmd",
    "jod",
    "jpy",
    "kes",
    "kgs",
    "khr",
    "kmf",
    "krw",
    "kwd",
    "kyd",
    "kzt",
    "lak",
    "lbp",
    "lkr",
    "lrd",
    "lsl",
    "mad",
    "mdl",
    "mga",
    "mkd",
    "mmk",
    "mnt",
    "mop",
    "mur",
    "mvr",
    "mwk",
    "mxn",
    "myr",
    "mzn",
    "nad",
    "ngn",
    "nio",
    "nok",
    "npr",
    "nzd",
    "omr",
    "pab",
    "pen",
    "pgk",
    "php",
    "pkr",
    "pln",
    "pyg",
    "qar",
    "ron",
    "rsd",
    "rub",
    "rwf",
    "sar",
    "sbd",
    "scr",
    "sek",
    "sgd",
    "shp",
    "sle",
    "sll",
    "sos",
    "srd",
    "std",
    "szl",
    "thb",
    "tjs",
    "tnd",
    "top",
    "try",
    "ttd",
    "twd",
    "tzs",
    "uah",
    "ugx",
    "uyu",
    "uzs",
    "vef",
    "vnd",
    "vuv",
    "wst",
    "xaf",
    "xcd",
    "xcg",
    "xof",
    "xpf",
    "yer",
    "zar",
    "zmw",
    "zwl",
  ].map((c) => c.toLowerCase()),
);

export function normalizeCurrencyCode(raw: string): string {
  return raw.trim().toLowerCase();
}

export function isStripeChargeCurrencySupported(code: string): boolean {
  const c = normalizeCurrencyCode(code);
  return /^[a-z]{3}$/.test(c) && STRIPE_CARD_CURRENCIES.has(c);
}

export function amountToStripeMinorUnits(amount: number, currency: string): number {
  const c = normalizeCurrencyCode(currency);
  if (!Number.isFinite(amount) || amount < 0) return 0;
  if (STRIPE_ZERO_DECIMAL_CURRENCIES.has(c)) {
    return Math.round(amount);
  }
  return Math.round(amount * 100);
}

export function minorUnitsToDisplayAmount(minor: number, currency: string): number {
  const c = normalizeCurrencyCode(currency);
  if (STRIPE_ZERO_DECIMAL_CURRENCIES.has(c)) return minor;
  return minor / 100;
}
