import Link from "next/link";

import { Card, CardContent } from "@/components/ui/card";
import { requireWorkspacePermissionActor } from "@/lib/permissions/require-workspace-permission";
import { canExportReports } from "@/lib/reports/report-export-access";
import { isReportKey, getReportDefinition } from "@/lib/reports/report-registry";
import { listReportExportHistory } from "@/services/reports/report-service";

export default async function ReportExportHistoryPage() {
  const actor = await requireWorkspacePermissionActor();
  const { userId } = actor;
  if (!canExportReports(actor)) {
    return (
      <Card className="border-border/80 shadow-sm">
        <CardContent className="py-8 text-center text-sm text-muted-foreground">
          You do not have permission to view report export history.
        </CardContent>
      </Card>
    );
  }
  const history = await listReportExportHistory(userId, 100);

  if (history.length === 0) {
    return (
      <div className="space-y-4">
        <h1 className="text-2xl font-semibold">Recent exports</h1>
        <Card className="border-border/80 shadow-sm">
          <CardContent className="space-y-2 py-8 text-center text-sm text-muted-foreground">
            <p className="text-base font-medium text-foreground">No exports yet</p>
            <p>Export a report to create history.</p>
            <Link
              href="/dashboard/reports/library"
              className="inline-flex rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"
            >
              Open report library
            </Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <h1 className="text-2xl font-semibold">Recent exports</h1>
      <Card className="border-border/80 shadow-sm">
        <CardContent className="p-0">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border/80 text-left">
                <th className="px-3 py-2 font-medium">When</th>
                <th className="px-3 py-2 font-medium">Report</th>
                <th className="px-3 py-2 font-medium">File</th>
                <th className="px-3 py-2 font-medium">Rows</th>
                <th className="px-3 py-2 font-medium">Generated by</th>
              </tr>
            </thead>
            <tbody>
              {history.map((r) => {
                const key = r.type.replace(/^report:/, "");
                const def = isReportKey(key) ? getReportDefinition(key) : null;
                return (
                  <tr key={r.id} className="border-b border-border/40">
                    <td className="px-3 py-2 text-muted-foreground">
                      {r.createdAt.toISOString().replace("T", " ").slice(0, 19)}
                    </td>
                    <td className="px-3 py-2">{def?.title ?? r.type}</td>
                    <td className="px-3 py-2">{r.fileName}</td>
                    <td className="px-3 py-2">{r.rowCount.toLocaleString()}</td>
                    <td className="px-3 py-2 text-muted-foreground">{r.actorEmail ?? "—"}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </CardContent>
      </Card>
    </div>
  );
}
