import type { PlaybookTemplateSeed } from "@/lib/playbooks/playbook-types";

/**
 * System playbook templates. These are seeded into the `playbooks`
 * table on first use of `ensureSystemPlaybooks(userId)` and kept
 * fresh on subsequent calls. The original `OPERATIONS_PLAYBOOKS`
 * constants remain untouched in `lib/operations-playbooks.ts` so
 * downstream readers don't break.
 */
export const SYSTEM_PLAYBOOK_TEMPLATES: PlaybookTemplateSeed[] = [
  {
    slug: "restaurant-daily-prep",
    title: "Restaurant daily prep",
    description: "Service-focused prep with purchasing guardrails.",
    type: "DAILY_OPERATIONS",
    businessModes: ["RESTAURANT"],
    recommendedModules: ["today", "orders", "production", "ingredient_demand", "purchasing", "tasks"],
    defaultRoles: ["manager", "kitchen_lead"],
    triggerType: "DAILY",
    recurrenceRule: "FREQ=DAILY",
    steps: [
      {
        title: "Scan Today board for open tickets",
        description: "Quick pass over Today to spot blockers before service.",
        recommendedRole: "manager",
        moduleKey: "today",
        actionRoute: "/dashboard/today",
        estimatedMinutes: 5,
        checklist: ["Active orders", "Failed webhooks", "Open tasks"],
      },
      {
        title: "Refresh prep list in Production",
        description: "Confirm production batches for tonight's service.",
        recommendedRole: "kitchen_lead",
        moduleKey: "production",
        actionRoute: "/dashboard/production",
        estimatedMinutes: 10,
        taskTemplate: { title: "Refresh prep list", priority: "HIGH", estimatedMinutes: 15 },
      },
      {
        title: "Check ingredient demand vs purchasing",
        description: "Reconcile expected ingredient usage against open purchase orders.",
        recommendedRole: "manager",
        moduleKey: "ingredient_demand",
        actionRoute: "/dashboard/inventory/demand",
        estimatedMinutes: 10,
      },
      {
        title: "Brief staff tasks for service",
        recommendedRole: "manager",
        moduleKey: "tasks",
        actionRoute: "/dashboard/tasks",
        estimatedMinutes: 10,
        required: false,
      },
      {
        title: "Review service risks",
        description: "Take 1 minute to flag any risks for the executive dashboard.",
        recommendedRole: "manager",
        moduleKey: "today",
        actionRoute: "/dashboard/executive/risks",
        estimatedMinutes: 5,
        required: false,
      },
    ],
  },
  {
    slug: "meal-prep-weekly-cycle",
    title: "Meal prep weekly cycle",
    description: "Preorder window → production day → packing → routes.",
    type: "WEEKLY_CYCLE",
    businessModes: ["MEAL_PREP"],
    recommendedModules: [
      "menus", "order_hub", "production", "packing_verify", "routes", "reports",
    ],
    defaultRoles: ["manager", "kitchen_lead", "packer", "driver"],
    triggerType: "WEEKLY",
    recurrenceRule: "FREQ=WEEKLY;BYDAY=SU",
    steps: [
      {
        title: "Confirm weekly menu and cutoff",
        recommendedRole: "manager",
        moduleKey: "menus",
        actionRoute: "/dashboard/menus",
        estimatedMinutes: 5,
      },
      {
        title: "Review order exceptions",
        recommendedRole: "manager",
        moduleKey: "order_hub",
        actionRoute: "/dashboard/order-hub",
        estimatedMinutes: 10,
      },
      {
        title: "Generate production by prepared date",
        recommendedRole: "kitchen_lead",
        moduleKey: "production",
        actionRoute: "/dashboard/production",
        estimatedMinutes: 20,
        taskTemplate: { title: "Generate production for the week", priority: "HIGH" },
      },
      {
        title: "Run packing verify",
        recommendedRole: "packer",
        moduleKey: "packing_verify",
        actionRoute: "/dashboard/packing/verify",
        estimatedMinutes: 30,
      },
      {
        title: "Load routes",
        recommendedRole: "driver",
        moduleKey: "routes",
        actionRoute: "/dashboard/routes",
        estimatedMinutes: 15,
      },
      {
        title: "Review weekly report",
        recommendedRole: "manager",
        moduleKey: "reports",
        actionRoute: "/dashboard/reports",
        estimatedMinutes: 10,
        required: false,
      },
    ],
  },
  {
    slug: "catering-event-workflow",
    title: "Catering event workflow",
    description: "Quote to execution with CRM context.",
    type: "EVENT_WORKFLOW",
    businessModes: ["CATERING"],
    recommendedModules: ["catering_quotes", "calendar", "production", "tasks", "routes", "customers"],
    defaultRoles: ["sales", "manager", "kitchen_lead", "driver"],
    triggerType: "EVENT_DATE",
    steps: [
      {
        title: "Review catering quotes in pipeline",
        recommendedRole: "sales",
        moduleKey: "catering_quotes",
        actionRoute: "/dashboard/catering-quotes",
        estimatedMinutes: 10,
      },
      {
        title: "Lock guest count and menu",
        recommendedRole: "sales",
        moduleKey: "catering_quotes",
        actionRoute: "/dashboard/catering-quotes",
        estimatedMinutes: 15,
      },
      {
        title: "Convert accepted quote to production tasks",
        recommendedRole: "manager",
        moduleKey: "production",
        actionRoute: "/dashboard/production",
        estimatedMinutes: 20,
        taskTemplate: { title: "Convert accepted quote into production", priority: "HIGH" },
      },
      {
        title: "Plan packing / loadout",
        recommendedRole: "kitchen_lead",
        moduleKey: "packing",
        actionRoute: "/dashboard/packing",
        estimatedMinutes: 15,
      },
      {
        title: "Plan routes and setup tasks for event day",
        recommendedRole: "driver",
        moduleKey: "routes",
        actionRoute: "/dashboard/routes",
        estimatedMinutes: 15,
      },
    ],
  },
  {
    slug: "bakery-preorder-day",
    title: "Bakery preorder day",
    description: "Batch production with pickup discipline.",
    type: "PREORDER_WORKFLOW",
    businessModes: ["BAKERY"],
    recommendedModules: ["menus", "production", "labels", "packing", "routes"],
    defaultRoles: ["manager", "kitchen_lead", "packer"],
    triggerType: "MENU_CUTOFF",
    steps: [
      {
        title: "Close preorder window",
        recommendedRole: "manager",
        moduleKey: "menus",
        actionRoute: "/dashboard/menus",
        estimatedMinutes: 5,
      },
      {
        title: "Sequence batches",
        recommendedRole: "kitchen_lead",
        moduleKey: "production",
        actionRoute: "/dashboard/production",
        estimatedMinutes: 30,
        taskTemplate: { title: "Sequence today's batches", priority: "HIGH" },
      },
      {
        title: "Print allergen / nutrition labels",
        recommendedRole: "kitchen_lead",
        moduleKey: "labels",
        actionRoute: "/dashboard/nutrition-labels",
        estimatedMinutes: 15,
      },
      {
        title: "Run packing verify",
        recommendedRole: "packer",
        moduleKey: "packing_verify",
        actionRoute: "/dashboard/packing/verify",
        estimatedMinutes: 20,
      },
      {
        title: "Stage pickup slots",
        recommendedRole: "manager",
        moduleKey: "routes",
        actionRoute: "/dashboard/routes",
        estimatedMinutes: 10,
        required: false,
      },
    ],
  },
  {
    slug: "cafe-morning-setup",
    title: "Café morning setup",
    description: "Baked goods, coffee line, specials, and preorder pickups.",
    type: "OPENING_CHECKLIST",
    businessModes: ["CAFE"],
    recommendedModules: ["today", "production", "menus", "purchasing", "tasks"],
    defaultRoles: ["manager", "kitchen_lead"],
    triggerType: "DAILY",
    recurrenceRule: "FREQ=DAILY",
    steps: [
      {
        title: "Warm ovens and par-bake schedule",
        recommendedRole: "kitchen_lead",
        moduleKey: "production",
        actionRoute: "/dashboard/production",
        estimatedMinutes: 15,
      },
      {
        title: "Stock milk, syrups, cups",
        recommendedRole: "manager",
        moduleKey: "purchasing",
        actionRoute: "/dashboard/purchasing",
        estimatedMinutes: 10,
      },
      {
        title: "Publish daily specials",
        recommendedRole: "manager",
        moduleKey: "menus",
        actionRoute: "/dashboard/menus",
        estimatedMinutes: 10,
      },
      {
        title: "Clear pickup shelf and confirm rush tasks",
        recommendedRole: "manager",
        moduleKey: "tasks",
        actionRoute: "/dashboard/tasks",
        estimatedMinutes: 5,
      },
    ],
  },
  {
    slug: "bar-event-night",
    title: "Bar event night",
    description: "Event setup, beverage pars, garnishes, and responsible service.",
    type: "EVENT_WORKFLOW",
    businessModes: ["BAR"],
    recommendedModules: ["today", "catering_quotes", "costing", "tasks", "orders", "calendar"],
    defaultRoles: ["manager", "sales"],
    triggerType: "EVENT_DATE",
    steps: [
      {
        title: "Review private bookings and deposits",
        recommendedRole: "sales",
        moduleKey: "catering_quotes",
        actionRoute: "/dashboard/catering-quotes",
        estimatedMinutes: 10,
      },
      {
        title: "Par ice, garnishes, glassware",
        recommendedRole: "manager",
        moduleKey: "costing",
        actionRoute: "/dashboard/costing",
        estimatedMinutes: 15,
        taskTemplate: { title: "Par ice, garnishes, glassware", priority: "HIGH" },
      },
      {
        title: "Assign floor and bar-back tasks",
        recommendedRole: "manager",
        moduleKey: "tasks",
        actionRoute: "/dashboard/tasks",
        estimatedMinutes: 10,
      },
      {
        title: "Post-close inventory spot check",
        recommendedRole: "manager",
        moduleKey: "today",
        actionRoute: "/dashboard/today",
        estimatedMinutes: 10,
        required: false,
      },
      {
        title: "Lock POS placeholder",
        recommendedRole: "manager",
        moduleKey: "orders",
        actionRoute: "/dashboard/orders",
        estimatedMinutes: 5,
        required: false,
      },
    ],
  },
  {
    slug: "ghost-kitchen-rush",
    title: "Ghost kitchen rush",
    description: "Channel surge with brand-aware production and sync hygiene.",
    type: "SERVICE_SHIFT",
    businessModes: ["GHOST_KITCHEN", "CLOUD_KITCHEN", "MULTI_BRAND"],
    recommendedModules: [
      "order_hub", "brands", "production", "packing_verify", "sales_channels", "integrations",
    ],
    defaultRoles: ["manager", "kitchen_lead", "packer"],
    triggerType: "ORDER_VOLUME",
    steps: [
      {
        title: "Triage Order Hub by brand and time",
        recommendedRole: "manager",
        moduleKey: "order_hub",
        actionRoute: "/dashboard/order-hub",
        estimatedMinutes: 10,
      },
      {
        title: "Balance production stations",
        recommendedRole: "kitchen_lead",
        moduleKey: "production",
        actionRoute: "/dashboard/production",
        estimatedMinutes: 15,
      },
      {
        title: "Run packing verify for every outbound bag",
        recommendedRole: "packer",
        moduleKey: "packing_verify",
        actionRoute: "/dashboard/packing/verify",
        estimatedMinutes: 20,
      },
      {
        title: "Review failed channel sync rows",
        recommendedRole: "manager",
        moduleKey: "integrations",
        actionRoute: "/dashboard/integrations",
        estimatedMinutes: 10,
      },
    ],
  },
];

export function findTemplateBySlug(slug: string): PlaybookTemplateSeed | undefined {
  return SYSTEM_PLAYBOOK_TEMPLATES.find((t) => t.slug === slug);
}
