/** QC audit event types (stored in `PackingQcEvent.eventType`). */
export const QC_EVENT = {
  TOKEN_SCANNED: "TOKEN_SCANNED",
  SESSION_STARTED: "SESSION_STARTED",
  SESSION_COMPLETED: "SESSION_COMPLETED",
  ITEM_VERIFIED: "ITEM_VERIFIED",
  ITEM_INCREMENT: "ITEM_INCREMENT",
  ITEM_MISSING: "ITEM_MISSING",
  ITEM_WRONG: "ITEM_WRONG",
  ITEM_DAMAGED: "ITEM_DAMAGED",
  ITEM_EXTRA: "ITEM_EXTRA",
  ITEM_SUBSTITUTED: "ITEM_SUBSTITUTED",
  ALLERGEN_CHECKED: "ALLERGEN_CHECKED",
  LABEL_CHECKED: "LABEL_CHECKED",
  ISSUE_OPENED: "ISSUE_OPENED",
  ISSUE_RESOLVED: "ISSUE_RESOLVED",
  SENT_BACK_PACKING: "SENT_BACK_PACKING",
  SENT_BACK_PRODUCTION: "SENT_BACK_PRODUCTION",
  SUPERVISOR_OVERRIDE: "SUPERVISOR_OVERRIDE",
  ORDER_STATUS_UPDATED: "ORDER_STATUS_UPDATED",
  PACKING_TASKS_UPDATED: "PACKING_TASKS_UPDATED",
} as const;

export type QcEventType = (typeof QC_EVENT)[keyof typeof QC_EVENT];
