import {
  AlertTriangle,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Building2,
  CalendarDays,
  CalendarRange,
  Cable,
  ChefHat,
  ClipboardList,
  Clock,
  Code2,
  Coins,
  CreditCard,
  FileSpreadsheet,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  ListTodo,
  HeartPulse,
  MenuSquare,
  MonitorDot,
  Package,
  Plug,
  Repeat,
  Rocket,
  Route,
  ScanBarcode,
  ScanLine,
  LayoutList,
  Link2,
  Mail,
  MapPin,
  MessageSquare,
  Radio,
  Settings,
  Settings2,
  Shield,
  ShoppingBag,
  TrendingDown,
  Wallet,
  Zap,
  Sparkles,
  Star,
  Store,
  Sun,
  Truck,
  Upload,
  UserCircle,
  Users,
  Wheat,
} from "lucide-react";

import type { NavGroupDef } from "@/lib/navigation/nav-types";

/**
 * Final sidebar IA — fewer top-level groups, clearer operator story.
 * Labels still flow through `navLabelForBusinessType` via `labelKey`.
 */
export const FINAL_NAVIGATION_GROUPS: NavGroupDef[] = [
  {
    id: "core",
    title: "Core",
    links: [
      { href: "/dashboard/today", labelKey: "nav.today", icon: Sun },
      { href: "/dashboard", labelKey: "nav.dashboard", icon: LayoutDashboard },
      { href: "/dashboard/orders", labelKey: "nav.orders", icon: Package },
      { href: "/dashboard/pos", labelKey: "nav.posTerminal", icon: ScanBarcode },
      { href: "/dashboard/pos/tabs", labelKey: "nav.posTabs", icon: LayoutList },
      { href: "/dashboard/pos/handheld", labelKey: "nav.posHandheld", icon: ScanBarcode },
    ],
  },
  {
    id: "operations",
    title: "Operations",
    links: [
      { href: "/dashboard/tables", labelKey: "nav.tables", icon: LayoutGrid },
      { href: "/dashboard/production", labelKey: "nav.production", icon: ChefHat },
      { href: "/dashboard/kitchen", labelKey: "nav.kitchen", icon: MonitorDot },
      { href: "/dashboard/packing", labelKey: "nav.packing", icon: Truck },
      { href: "/dashboard/packing/verify", labelKey: "nav.packingVerify", icon: ScanLine },
      { href: "/dashboard/routes", labelKey: "nav.routes", icon: Route },
      { href: "/dashboard/routes/fleet", labelKey: "nav.fleetMap", icon: MapPin },
      { href: "/dashboard/routes/optimize", labelKey: "nav.routeOptimize", icon: Zap },
      { href: "/dashboard/settings/delivery-zones", labelKey: "nav.deliveryZones", icon: MapPin },
      { href: "/dashboard/tasks", labelKey: "nav.tasks", icon: ListTodo },
      { href: "/dashboard/locations", labelKey: "nav.locations", icon: Building2 },
      { href: "/dashboard/calendar", labelKey: "nav.calendar", icon: CalendarDays },
    ],
  },
  {
    id: "commerce",
    title: "Commerce",
    links: [
      { href: "/dashboard/storefront", labelKey: "nav.storefront", icon: Store },
      { href: "/dashboard/storefront/pickup-windows", labelKey: "nav.pickupWindows", icon: Clock },
      { href: "/dashboard/storefront/gift-cards", labelKey: "nav.giftCards", icon: CreditCard },
      { href: "/dashboard/storefront/loyalty", labelKey: "nav.loyalty", icon: HeartPulse },
      { href: "/dashboard/storefront/reservations", labelKey: "nav.reservations", icon: CalendarDays },
      { href: "/dashboard/storefront/marketing", labelKey: "nav.storefrontMarketing", icon: Rocket },
      { href: "/dashboard/storefront/reviews", labelKey: "nav.storefrontReviews", icon: Star },
      { href: "/dashboard/storefront/referrals", labelKey: "nav.referrals", icon: Repeat },
      { href: "/dashboard/storefront/schedule", labelKey: "nav.menuSchedule", icon: CalendarRange },
      { href: "/dashboard/storefront/inventory", labelKey: "nav.storefrontInventory", icon: Package },
      { href: "/dashboard/sales-channels", labelKey: "nav.integrations", icon: Plug },
      { href: "/dashboard/integrations/extensions", labelKey: "nav.extensions", icon: Plug },
      { href: "/dashboard/integrations/outbound-webhooks", labelKey: "nav.outboundWebhooks", icon: Plug },
      { href: "/dashboard/integrations/oauth-apps", labelKey: "nav.oauthApps", icon: Plug },
      { href: "/dashboard/integrations/doordash", labelKey: "nav.doordash", icon: Truck },
      { href: "/dashboard/integrations/grubhub", labelKey: "nav.grubhub", icon: Truck },
      { href: "/dashboard/orders/hub", labelKey: "nav.ordersHub", icon: LayoutGrid },
      { href: "/dashboard/order-hub", labelKey: "nav.orderHub", icon: LayoutGrid },
      { href: "/dashboard/receivables", labelKey: "nav.receivables", icon: Wallet },
      { href: "/dashboard/product-mapping", labelKey: "nav.productMapping", icon: MenuSquare },
    ],
  },
  {
    id: "menus",
    title: "Menus",
    links: [
      { href: "/dashboard/menus", labelKey: "nav.menus", icon: MenuSquare },
      { href: "/dashboard/products", labelKey: "nav.products", icon: ShoppingBag },
      { href: "/dashboard/menu-planner", labelKey: "nav.menuPlanner", icon: CalendarRange },
      { href: "/dashboard/brands", labelKey: "nav.brands", icon: Store },
      { href: "/dashboard/brands/command-center", labelKey: "nav.brandCommandCenter", icon: BarChart3 },
      { href: "/dashboard/nutrition-labels", labelKey: "nav.nutritionLabels", icon: Wheat },
    ],
  },
  {
    id: "customers",
    title: "Customers",
    links: [
      { href: "/dashboard/customers", labelKey: "nav.customers", icon: Users },
      { href: "/dashboard/customers/feedback", labelKey: "nav.customerFeedback", icon: MessageSquare },
      { href: "/dashboard/customers/churn-risk", labelKey: "nav.churnRisk", icon: TrendingDown },
      { href: "/dashboard/customers/loyalty", labelKey: "nav.loyalty", icon: Users },
      { href: "/dashboard/referrals", labelKey: "nav.referrals", icon: Link2 },
      { href: "/dashboard/gift-cards", labelKey: "nav.giftCards", icon: CreditCard },
      { href: "/dashboard/meal-plans", labelKey: "nav.mealSubscriptions", icon: Repeat },
      { href: "/dashboard/catering-quotes", labelKey: "nav.catering", icon: ClipboardList },
    ],
  },
  {
    id: "inventoryFinance",
    title: "Inventory & finance",
    links: [
      { href: "/dashboard/inventory/demand", labelKey: "nav.inventoryDemand", icon: Package },
      { href: "/dashboard/inventory/pos-impacts", labelKey: "nav.inventoryPosImpacts", icon: Package },
      { href: "/dashboard/inventory/waste", labelKey: "nav.inventoryWaste", icon: Package },
      { href: "/dashboard/inventory/counts", labelKey: "nav.inventoryCounts", icon: Package },
      { href: "/dashboard/purchasing", labelKey: "nav.purchasing", icon: ShoppingBag },
      { href: "/dashboard/purchasing/bulk-pricing", labelKey: "nav.bulkPricing", icon: Coins },
      { href: "/dashboard/purchasing/direct-ordering", labelKey: "nav.directOrdering", icon: Truck },
      { href: "/dashboard/accounting/invoices", labelKey: "nav.apInvoices", icon: FileSpreadsheet },
      { href: "/dashboard/accounting/vendor-payments", labelKey: "nav.vendorPayments", icon: Wallet },
      { href: "/dashboard/accounting/bank-reconciliation", labelKey: "nav.bankReconciliation", icon: FileSpreadsheet },
      { href: "/dashboard/accounting/cash-counts", labelKey: "nav.cashCounts", icon: Coins },
      { href: "/dashboard/inventory/receiving", labelKey: "nav.receivingReconciliation", icon: Package },
      { href: "/dashboard/costing", labelKey: "nav.costing", icon: Coins },
      { href: "/dashboard/costing/theft", labelKey: "nav.theftDetection", icon: AlertTriangle },
      { href: "/dashboard/billing", labelKey: "nav.billing", icon: CreditCard },
      { href: "/dashboard/import-export", labelKey: "nav.importExport", icon: Upload },
    ],
  },
  {
    id: "foodSafety",
    title: "Food safety",
    links: [
      { href: "/dashboard/food-safety", labelKey: "nav.foodSafetyOverview", icon: Shield },
      { href: "/dashboard/food-safety/temperature", labelKey: "nav.foodSafetyTemperature", icon: HeartPulse },
      { href: "/dashboard/food-safety/checklists", labelKey: "nav.foodSafetyChecklists", icon: ClipboardList },
      { href: "/dashboard/food-safety/audits", labelKey: "nav.foodSafetyAudits", icon: Shield },
      { href: "/dashboard/food-safety/allergens", labelKey: "nav.allergens", icon: AlertTriangle },
      { href: "/dashboard/food-safety/iot-devices", labelKey: "nav.iotDevices", icon: Radio },
    ],
  },
  {
    id: "marketing",
    title: "Marketing",
    links: [
      { href: "/dashboard/marketing/email-campaigns", labelKey: "nav.emailCampaigns", icon: Mail },
      { href: "/dashboard/marketing/holiday-packages", labelKey: "nav.holidayPackages", icon: Sparkles },
    ],
  },
  {
    id: "insights",
    title: "Insights",
    links: [
      { href: "/dashboard/analytics", labelKey: "nav.analytics", icon: BarChart3 },
      { href: "/dashboard/forecast", labelKey: "nav.forecast", icon: Sparkles },
      { href: "/dashboard/reports", labelKey: "nav.reports", icon: FileSpreadsheet },
      { href: "/dashboard/reports/tax", labelKey: "nav.taxReports", icon: FileSpreadsheet },
      { href: "/dashboard/reports/labor", labelKey: "nav.laborReports", icon: Users },
      { href: "/dashboard/reports/financial/pnl", labelKey: "nav.restaurantPnl", icon: Coins },
      { href: "/dashboard/reports/menu-engineering", labelKey: "nav.menuEngineering", icon: BarChart3 },
      { href: "/dashboard/forecast/ai", labelKey: "nav.aiForecast", icon: Sparkles },
      { href: "/dashboard/franchise/royalties", labelKey: "nav.franchiseRoyalties", icon: Building2 },
      { href: "/dashboard/commissary/transfers", labelKey: "nav.commissaryTransfers", icon: Truck },
      { href: "/dashboard/production/calendar", labelKey: "nav.productionCalendar", icon: CalendarDays },
      { href: "/dashboard/recipes/yield", labelKey: "nav.yieldManagement", icon: Wheat },
      { href: "/dashboard/operations/checklists", labelKey: "nav.operations", icon: ClipboardList },
      { href: "/dashboard/executive", labelKey: "nav.executive", icon: BarChart3 },
      { href: "/dashboard/copilot", labelKey: "nav.copilot", icon: Bot },
    ],
  },
  {
    id: "setup",
    title: "Setup",
    links: [
      { href: "/dashboard/implementation", labelKey: "nav.implementation", icon: ClipboardList },
      { href: "/dashboard/launch-wizard", labelKey: "nav.launchWizard", icon: Rocket },
      { href: "/dashboard/import-center", labelKey: "nav.importCenter", icon: Upload },
      { href: "/dashboard/import-center/migrate", labelKey: "nav.migrationWizard", icon: Upload },
      { href: "/dashboard/go-live", labelKey: "nav.goLive", icon: Sparkles },
      { href: "/dashboard/training", labelKey: "nav.training", icon: UserCircle },
      { href: "/dashboard/templates", labelKey: "nav.templates", icon: LayoutTemplate },
      { href: "/dashboard/playbooks", labelKey: "nav.playbooks", icon: BookOpen },
      { href: "/dashboard/demo/scenarios", labelKey: "nav.demoScenarios", icon: LayoutTemplate },
    ],
  },
  {
    id: "admin",
    title: "Admin",
    links: [
      { href: "/dashboard/staff", labelKey: "nav.staff", icon: UserCircle },
      { href: "/dashboard/staff/time-clock", labelKey: "nav.timeClock", icon: Clock },
      { href: "/dashboard/staff/schedule", labelKey: "nav.laborSchedule", icon: CalendarRange },
      { href: "/dashboard/staff/payroll", labelKey: "nav.payrollExport", icon: FileSpreadsheet },
      { href: "/dashboard/notifications", labelKey: "nav.notifications", icon: Bell },
      { href: "/dashboard/notifications/rules", labelKey: "nav.notificationRules", icon: Settings2 },
      { href: "/dashboard/settings/notifications/sms", labelKey: "nav.smsNotifications", icon: MessageSquare },
      { href: "/dashboard/settings/notifications/whatsapp", labelKey: "nav.whatsappNotifications", icon: MessageSquare },
      { href: "/dashboard/settings/notifications/push", labelKey: "nav.pushNotifications", icon: Bell },
      { href: "/dashboard/settings", labelKey: "nav.settings", icon: Settings },
      { href: "/dashboard/support", labelKey: "nav.support", icon: Bell },
      { href: "/dashboard/audit-logs", labelKey: "nav.auditLogs", icon: Settings2 },
      { href: "/dashboard/integration-health", labelKey: "nav.integrationHealth", icon: Cable },
      { href: "/dashboard/error-recovery", labelKey: "nav.errorRecovery", icon: AlertTriangle },
      { href: "/dashboard/system-health", labelKey: "nav.systemHealth", icon: HeartPulse },
      { href: "/dashboard/system-health/data-integrity", labelKey: "nav.dataIntegrity", icon: Shield },
    ],
  },
  {
    id: "internal",
    title: "Internal",
    links: [
      { href: "/dashboard/growth", labelKey: "nav.growth", icon: Rocket, ownerOnly: true },
      {
        href: "/dashboard/beta-applications",
        labelKey: "nav.betaApplications",
        icon: ClipboardList,
        ownerOnly: true,
      },
      { href: "/dashboard/partner", labelKey: "nav.partner", icon: Users, ownerOnly: true },
      { href: "/dashboard/developer", labelKey: "nav.developer", icon: Code2, ownerOnly: true },
    ],
  },
];
