#!/bin/bash
# Weekly pilot report scaffold — fill [placeholders] after team review.
# Usage: bash scripts/ops/weekly-pilot-report.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

BASE_URL="${PILOT_BASE_URL:-https://os-kitchen.com}"
WEEK=$(date +%V)
REPORT="docs/pilot-reports/week-${WEEK}-$(date +%Y-%m-%d).md"
mkdir -p docs/pilot-reports

HEALTH_JSON=$(curl -sS --max-time 15 "${BASE_URL}/api/health" 2>/dev/null || echo "{}")
HEALTH_DETAIL=$(echo "$HEALTH_JSON" | python3 -c "
import sys, json
d = json.load(sys.stdin)
lines = [f\"- Overall: **{d.get('status', 'unknown')}**\"]
for k, v in d.get('checks', {}).items():
    ok = v.get('ok') if isinstance(v, dict) else bool(v)
    lines.append(f\"- {k}: {'ok' if ok else 'FAIL'}\")
print(chr(10).join(lines) if lines else '- Overall: **N/A**')
" 2>/dev/null || echo "- Overall: **N/A**")

cat > "$REPORT" << EOF
# KitchenOS Pilot — Week ${WEEK} Report

**Date:** $(date +%Y-%m-%d)  
**Period:** 7 days ending $(date +%Y-%m-%d)  
**Production:** ${BASE_URL}

---

## System Health

${HEALTH_DETAIL}

- Uptime (estimated): [e.g. 99.8% — from Vercel / status checks]
- Incidents (SEV-1/2): [count] — [links or summary]
- Deployments this week: [count] — [notable deploy SHA]
- Cron \`pilot-daily-health\`: [all ok / N degraded days]

---

## Operators

| Metric | Value |
|--------|-------|
| Total invited | [count] |
| Activated (≥1 order, all time) | [count] |
| Active this week (≥1 session) | [count] |
| New activations this week | [count] |
| Churned / paused | [count] |

**Operator notes:** [themes from check-ins]

---

## Orders

| Metric | Value |
|--------|-------|
| Total orders (week) | [count] |
| Avg orders / active kitchen | [count] |
| Storefront orders | [count] |
| POS orders | [count] |

---

## Revenue

| Metric | Value |
|--------|-------|
| MRR | \$[amount] |
| New subscriptions | [count] |
| Failed payments | [count] |
| Refunds / disputes | [count] |

---

## Support

| Metric | Value |
|--------|-------|
| Tickets opened | [count] |
| Avg first response time | [time] |
| Top issue | [description] |

---

## Product / roadmap

- Roadmap quarter focus: [Q2 pilot item from PRODUCT_ROADMAP_2026.md]
- Feedback forms completed: [count]
- NPS (if surveyed): [score]

---

## Actions for next week

1. 
2. 
3. 

---

## Notes

[Free text — blockers, wins, sales pipeline]

---

*Generated by \`scripts/ops/weekly-pilot-report.sh\`. Auto-filled health from \`/api/health\`; complete placeholders before Monday review.*
EOF

echo "Weekly report created: $REPORT"
echo "Fill in the [placeholders] with CRM, Stripe, and operator data."
