import type { PermissionKey } from "@/lib/permissions/permissions";

export type ActionMutationRisk = "low" | "medium" | "high" | "critical";

export type ActionMutationOperationEntry = {
  id: string;
  domain: string;
  actionModule: string;
  operation: string;
  permission: PermissionKey | "documented_exception";
  exceptionId?: string;
  risk: ActionMutationRisk;
};

/** Governed server action operations — one or two primary mutations per action module. */
export const ACTION_MUTATION_OPERATIONS: readonly ActionMutationOperationEntry[] = [
  { id: "account_deletion_request_account_deletion", domain: "account_deletion", actionModule: "actions/account-deletion.ts", operation: "requestAccountDeletionAction", permission: "orders.manage", risk: "high" },
  { id: "accounting_create_invoice", domain: "accounting", actionModule: "actions/accounting/ap.ts", operation: "createInvoiceAction", permission: "reports.read.financial", risk: "medium" },
  { id: "accounting_match_invoice", domain: "accounting", actionModule: "actions/accounting/ap.ts", operation: "matchInvoiceAction", permission: "reports.read.financial", risk: "medium" },
  { id: "accounting_import_bank_csv", domain: "accounting", actionModule: "actions/accounting/bank-reconciliation.ts", operation: "importBankCsvAction", permission: "reports.read.financial", risk: "medium" },
  { id: "accounting_reconcile_bank_tx", domain: "accounting", actionModule: "actions/accounting/bank-reconciliation.ts", operation: "reconcileBankTxAction", permission: "reports.read.financial", risk: "medium" },
  { id: "accounting_submit_cash_count", domain: "accounting", actionModule: "actions/accounting/cash.ts", operation: "submitCashCountAction", permission: "reports.read.financial", risk: "medium" },
  { id: "accounting_upload_invoice_ocr", domain: "accounting", actionModule: "actions/accounting/invoice-ocr.ts", operation: "uploadInvoiceOcrAction", permission: "workspace.view", risk: "low" },
  { id: "accounting_refresh_pnl_snapshot", domain: "accounting", actionModule: "actions/accounting/pnl.ts", operation: "refreshPnlSnapshotAction", permission: "reports.read.financial", risk: "medium" },
  { id: "allergen_profile_upsert_allergen_profile_form", domain: "allergen_profile", actionModule: "actions/allergen-profile.ts", operation: "upsertAllergenProfileFormAction", permission: "customers.manage", risk: "high" },
  { id: "analytics_generate_analytics_snapshot", domain: "analytics", actionModule: "actions/analytics.ts", operation: "generateAnalyticsSnapshotAction", permission: "reports.read.financial", risk: "medium" },
  { id: "analytics_generate_analytics_snapshot_form", domain: "analytics", actionModule: "actions/analytics.ts", operation: "generateAnalyticsSnapshotFormAction", permission: "reports.read.financial", risk: "medium" },
  { id: "audit_center_load_more_audit_logs", domain: "audit_center", actionModule: "actions/audit-center.ts", operation: "loadMoreAuditLogsAction", permission: "workspace.view", risk: "low" },
  { id: "audit_center_get_audit_log_detail", domain: "audit_center", actionModule: "actions/audit-center.ts", operation: "getAuditLogDetailAction", permission: "workspace.view", risk: "low" },
  { id: "auth_sign_in", domain: "auth", actionModule: "actions/auth.ts", operation: "signInAction", permission: "workspace.view", risk: "low" },
  { id: "auth_sign_up", domain: "auth", actionModule: "actions/auth.ts", operation: "signUpAction", permission: "workspace.view", risk: "low" },
  { id: "billing_set_entitlement_override", domain: "billing", actionModule: "actions/billing.ts", operation: "setEntitlementOverrideAction", permission: "billing.manage", risk: "critical" },
  { id: "billing_clear_entitlement_override", domain: "billing", actionModule: "actions/billing.ts", operation: "clearEntitlementOverrideAction", permission: "billing.manage", risk: "critical" },
  { id: "brands_update_brand_details_form", domain: "brands", actionModule: "actions/brands.ts", operation: "updateBrandDetailsFormAction", permission: "orders.manage", risk: "high" },
  { id: "brands_update_brand_lifecycle_form", domain: "brands", actionModule: "actions/brands.ts", operation: "updateBrandLifecycleFormAction", permission: "orders.manage", risk: "high" },
  { id: "capital_lender_offers_consent_capital_lender_offer", domain: "capital_lender_offers", actionModule: "actions/capital-lender-offers.ts", operation: "consentCapitalLenderOfferAction", permission: "billing.manage", risk: "critical" },
  { id: "capital_lender_offers_select_capital_referral_offer", domain: "capital_lender_offers", actionModule: "actions/capital-lender-offers.ts", operation: "selectCapitalReferralOfferAction", permission: "billing.manage", risk: "critical" },
  { id: "capital_partner_billing_sync_capital_partner_billing_statements", domain: "capital_partner_billing", actionModule: "actions/capital-partner-billing.ts", operation: "syncCapitalPartnerBillingStatementsAction", permission: "billing.manage", risk: "critical" },
  { id: "capital_partner_billing_finalize_capital_partner_billing_statement", domain: "capital_partner_billing", actionModule: "actions/capital-partner-billing.ts", operation: "finalizeCapitalPartnerBillingStatementAction", permission: "billing.manage", risk: "critical" },
  { id: "capital_resources_submit_capital_interest", domain: "capital_resources", actionModule: "actions/capital-resources.ts", operation: "submitCapitalInterestAction", permission: "billing.manage", risk: "critical" },
  { id: "capital_resources_log_capital_partner_view", domain: "capital_resources", actionModule: "actions/capital-resources.ts", operation: "logCapitalPartnerViewAction", permission: "billing.manage", risk: "critical" },
  { id: "catering_quotes_create_catering_quote", domain: "catering_quotes", actionModule: "actions/catering-quotes.ts", operation: "createCateringQuoteAction", permission: "orders.manage", risk: "high" },
  { id: "catering_quotes_create_catering_quote_form", domain: "catering_quotes", actionModule: "actions/catering-quotes.ts", operation: "createCateringQuoteFormAction", permission: "orders.manage", risk: "high" },
  { id: "catering_create_catering_quote", domain: "catering", actionModule: "actions/catering.ts", operation: "createCateringQuoteAction", permission: "orders.manage", risk: "high" },
  { id: "catering_mark_quote_sent", domain: "catering", actionModule: "actions/catering.ts", operation: "markQuoteSentAction", permission: "orders.manage", risk: "high" },
  { id: "channel_certification_run_channel_certification", domain: "channel_certification", actionModule: "actions/channel-certification.ts", operation: "runChannelCertificationAction", permission: "orders.manage", risk: "high" },
  { id: "channel_certification_record_certification_sign_off", domain: "channel_certification", actionModule: "actions/channel-certification.ts", operation: "recordCertificationSignOffAction", permission: "orders.manage", risk: "high" },
  { id: "commissary_create_transfer", domain: "commissary", actionModule: "actions/commissary.ts", operation: "createTransferAction", permission: "orders.manage", risk: "high" },
  { id: "copilot_chat_turn", domain: "copilot", actionModule: "actions/copilot.ts", operation: "chatTurnAction", permission: "documented_exception", exceptionId: "copilot_capability_matrix", risk: "medium" },
  { id: "copilot_create_draft", domain: "copilot", actionModule: "actions/copilot.ts", operation: "createActionDraftAction", permission: "documented_exception", exceptionId: "copilot_capability_matrix", risk: "medium" },
  { id: "costing_recalculate_cost_snapshots", domain: "costing", actionModule: "actions/costing.ts", operation: "recalculateCostSnapshotsAction", permission: "orders.manage", risk: "high" },
  { id: "costing_save_costing_settings", domain: "costing", actionModule: "actions/costing.ts", operation: "saveCostingSettingsAction", permission: "orders.manage", risk: "high" },
  { id: "cron_incidents_acknowledge_cron_incident_form", domain: "cron_incidents", actionModule: "actions/cron-incidents.ts", operation: "acknowledgeCronIncidentFormAction", permission: "orders.manage", risk: "high" },
  { id: "cron_incidents_clear_cron_incident_acknowledgement_form", domain: "cron_incidents", actionModule: "actions/cron-incidents.ts", operation: "clearCronIncidentAcknowledgementFormAction", permission: "orders.manage", risk: "high" },
  { id: "customer_subscription_create_customer_subscription", domain: "customer_subscription", actionModule: "actions/customer-subscription.ts", operation: "createCustomerSubscriptionAction", permission: "orders.manage", risk: "high" },
  { id: "customer_subscription_set_subscription_status", domain: "customer_subscription", actionModule: "actions/customer-subscription.ts", operation: "setSubscriptionStatusAction", permission: "orders.manage", risk: "high" },
  { id: "customers_create_customer", domain: "customers", actionModule: "actions/customers.ts", operation: "createCustomerAction", permission: "customers.manage", risk: "high" },
  { id: "customers_create_customer_form", domain: "customers", actionModule: "actions/customers.ts", operation: "createCustomerFormAction", permission: "customers.manage", risk: "high" },
  { id: "delivery_proof_upload_delivery_proof_form", domain: "delivery_proof", actionModule: "actions/delivery-proof.ts", operation: "uploadDeliveryProofFormAction", permission: "workspace.view", risk: "low" },
  { id: "delivery_route_create_delivery_route_from_orders", domain: "delivery_route", actionModule: "actions/delivery-route.ts", operation: "createDeliveryRouteFromOrdersAction", permission: "routes.manage", risk: "high" },
  { id: "delivery_route_create_delivery_route_from_orders_form", domain: "delivery_route", actionModule: "actions/delivery-route.ts", operation: "createDeliveryRouteFromOrdersFormAction", permission: "routes.manage", risk: "high" },
  { id: "demo_golden_scenario_seed_golden_scenario", domain: "demo_golden_scenario", actionModule: "actions/demo-golden-scenario.ts", operation: "seedGoldenScenarioAction", permission: "templates.manage", risk: "high" },
  { id: "demo_golden_scenario_reset_golden_scenario", domain: "demo_golden_scenario", actionModule: "actions/demo-golden-scenario.ts", operation: "resetGoldenScenarioAction", permission: "templates.manage", risk: "high" },
  { id: "developer_platform_create_platform_incident", domain: "developer_platform", actionModule: "actions/developer-platform.ts", operation: "createPlatformIncidentAction", permission: "orders.manage", risk: "high" },
  { id: "developer_platform_validate_environment_now", domain: "developer_platform", actionModule: "actions/developer-platform.ts", operation: "validateEnvironmentNowAction", permission: "orders.manage", risk: "high" },
  { id: "executive_refresh_executive_snapshot", domain: "executive", actionModule: "actions/executive.ts", operation: "refreshExecutiveSnapshotAction", permission: "executive.insights.manage", risk: "high" },
  { id: "executive_refresh_executive_snapshot_form", domain: "executive", actionModule: "actions/executive.ts", operation: "refreshExecutiveSnapshotFormAction", permission: "executive.insights.manage", risk: "high" },
  { id: "experiment_ethics_review_submit_ethics_review", domain: "experiment_ethics_review", actionModule: "actions/experiment-ethics-review.ts", operation: "submitEthicsReviewAction", permission: "orders.manage", risk: "high" },
  { id: "food_safety_log_temperature", domain: "food_safety", actionModule: "actions/food-safety.ts", operation: "logTemperatureAction", permission: "production.manage", risk: "high" },
  { id: "food_safety_create_checklist", domain: "food_safety", actionModule: "actions/food-safety.ts", operation: "createChecklistAction", permission: "workspace.view", risk: "low" },
  { id: "forecast_run_forecast", domain: "forecast", actionModule: "actions/forecast.ts", operation: "runForecastAction", permission: "reports.read.operations", risk: "medium" },
  { id: "forecast_run_forecast_form", domain: "forecast", actionModule: "actions/forecast.ts", operation: "runForecastFormAction", permission: "reports.read.operations", risk: "medium" },
  { id: "gift_cards_create_gift_card", domain: "gift_cards", actionModule: "actions/gift-cards.ts", operation: "createGiftCardAction", permission: "giftcards.manage", risk: "high" },
  { id: "go_live_create_go_live_project", domain: "go_live", actionModule: "actions/go-live.ts", operation: "createGoLiveProjectAction", permission: "orders.manage", risk: "high" },
  { id: "go_live_refresh_validation", domain: "go_live", actionModule: "actions/go-live.ts", operation: "refreshValidationAction", permission: "orders.manage", risk: "high" },
  { id: "implementation_center_create_implementation_project", domain: "implementation_center", actionModule: "actions/implementation-center.ts", operation: "createImplementationProjectAction", permission: "orders.manage", risk: "high" },
  { id: "implementation_center_update_implementation_status", domain: "implementation_center", actionModule: "actions/implementation-center.ts", operation: "updateImplementationStatusAction", permission: "orders.manage", risk: "high" },
  { id: "import_center_upload_import_csv", domain: "import_center", actionModule: "actions/import-center.ts", operation: "uploadImportCsvAction", permission: "workspace.view", risk: "low" },
  { id: "import_center_commit_import_job", domain: "import_center", actionModule: "actions/import-center.ts", operation: "commitImportJobAction", permission: "orders.manage", risk: "high" },
  { id: "import_export_validate_ingredient_import_preview", domain: "import_export", actionModule: "actions/import-export.ts", operation: "validateIngredientImportPreviewAction", permission: "workspace.view", risk: "low" },
  { id: "ingredient_declaration_upsert_ingredient_declaration_form", domain: "ingredient_declaration", actionModule: "actions/ingredient-declaration.ts", operation: "upsertIngredientDeclarationFormAction", permission: "orders.manage", risk: "high" },
  { id: "integration_menu_sync_force_uber_eats_menu_sync", domain: "integration_menu_sync", actionModule: "actions/integration-menu-sync.ts", operation: "forceUberEatsMenuSyncAction", permission: "orders.manage", risk: "high" },
  { id: "integration_menu_sync_test_door_dash_connection", domain: "integration_menu_sync", actionModule: "actions/integration-menu-sync.ts", operation: "testDoorDashConnectionAction", permission: "orders.manage", risk: "high" },
  { id: "integrations_request_door_dash_quote", domain: "integrations", actionModule: "actions/integrations/doordash.ts", operation: "requestDoorDashQuoteAction", permission: "integrations.manage", risk: "high" },
  { id: "integrations_create_door_dash_delivery", domain: "integrations", actionModule: "actions/integrations/doordash.ts", operation: "createDoorDashDeliveryAction", permission: "integrations.manage", risk: "high" },
  { id: "integrations_test_grubhub_order", domain: "integrations", actionModule: "actions/integrations/grubhub.ts", operation: "testGrubhubOrderAction", permission: "integrations.manage", risk: "high" },
  { id: "integrations_pull_inventory_sync", domain: "integrations", actionModule: "actions/integrations/inventory-sync.ts", operation: "pullInventorySyncAction", permission: "integrations.manage", risk: "high" },
  { id: "integrations_resolve_inventory_conflict", domain: "integrations", actionModule: "actions/integrations/inventory-sync.ts", operation: "resolveInventoryConflictAction", permission: "integrations.manage", risk: "high" },
  { id: "inventory_log_waste_event", domain: "inventory", actionModule: "actions/inventory.ts", operation: "logWasteEventAction", permission: "production.manage", risk: "high" },
  { id: "inventory_start_inventory_count", domain: "inventory", actionModule: "actions/inventory.ts", operation: "startInventoryCountAction", permission: "production.manage", risk: "high" },
  { id: "inventory_pull_cross_channel_inventory", domain: "inventory", actionModule: "actions/inventory/cross-channel-inventory.ts", operation: "pullCrossChannelInventoryAction", permission: "production.manage", risk: "high" },
  { id: "inventory_resolve_cross_channel_conflict", domain: "inventory", actionModule: "actions/inventory/cross-channel-inventory.ts", operation: "resolveCrossChannelConflictAction", permission: "production.manage", risk: "high" },
  { id: "kitchen_ai_run_a_i_order_forecast", domain: "kitchen_ai", actionModule: "actions/kitchen-ai.ts", operation: "runAIOrderForecastAction", permission: "kitchen.bump", risk: "medium" },
  { id: "kitchen_ai_run_a_i_menu_suggestions", domain: "kitchen_ai", actionModule: "actions/kitchen-ai.ts", operation: "runAIMenuSuggestionsAction", permission: "kitchen.bump", risk: "medium" },
  { id: "kitchen_daily_kds_fetch_daily_kds_orders", domain: "kitchen_daily_kds", actionModule: "actions/kitchen-daily-kds.ts", operation: "fetchDailyKdsOrdersAction", permission: "kitchen.bump", risk: "medium" },
  { id: "kitchen_daily_kds_bump_daily_kds_order", domain: "kitchen_daily_kds", actionModule: "actions/kitchen-daily-kds.ts", operation: "bumpDailyKdsOrderAction", permission: "kitchen.bump", risk: "medium" },
  { id: "kitchen_task_create_kitchen_task", domain: "kitchen_task", actionModule: "actions/kitchen-task.ts", operation: "createKitchenTaskAction", permission: "kitchen.bump", risk: "medium" },
  { id: "kitchen_task_update_kitchen_task_status", domain: "kitchen_task", actionModule: "actions/kitchen-task.ts", operation: "updateKitchenTaskStatusAction", permission: "kitchen.bump", risk: "medium" },
  { id: "label_print_queue_create_printed_label_job", domain: "label_print_queue", actionModule: "actions/label-print-queue.ts", operation: "createPrintedLabelJobAction", permission: "orders.manage", risk: "high" },
  { id: "label_print_queue_mark_printed_label_job", domain: "label_print_queue", actionModule: "actions/label-print-queue.ts", operation: "markPrintedLabelJobAction", permission: "orders.manage", risk: "high" },
  { id: "labor_generate_ai_schedule", domain: "labor", actionModule: "actions/labor/ai-scheduling.ts", operation: "generateAiScheduleAction", permission: "orders.manage", risk: "high" },
  { id: "labor_apply_ai_schedule", domain: "labor", actionModule: "actions/labor/ai-scheduling.ts", operation: "applyAiScheduleAction", permission: "orders.manage", risk: "high" },
  { id: "labor_create_shift", domain: "labor", actionModule: "actions/labor/schedule.ts", operation: "createShiftAction", permission: "orders.manage", risk: "high" },
  { id: "labor_update_shift", domain: "labor", actionModule: "actions/labor/schedule.ts", operation: "updateShiftAction", permission: "orders.manage", risk: "high" },
  { id: "labor_clock_in", domain: "labor", actionModule: "actions/labor/time-clock.ts", operation: "clockInAction", permission: "orders.manage", risk: "high" },
  { id: "labor_clock_out", domain: "labor", actionModule: "actions/labor/time-clock.ts", operation: "clockOutAction", permission: "orders.manage", risk: "high" },
  { id: "labor_save_tip_pool_rules", domain: "labor", actionModule: "actions/labor/tip-pooling.ts", operation: "saveTipPoolRulesAction", permission: "orders.manage", risk: "high" },
  { id: "locations_create_location", domain: "locations", actionModule: "actions/locations.ts", operation: "createLocationAction", permission: "workspace.settings", risk: "critical" },
  { id: "locations_create_location_form", domain: "locations", actionModule: "actions/locations.ts", operation: "createLocationFormAction", permission: "workspace.settings", risk: "critical" },
  { id: "loyalty_update_loyalty_program", domain: "loyalty", actionModule: "actions/loyalty.ts", operation: "updateLoyaltyProgramAction", permission: "loyalty.manage", risk: "high" },
  { id: "loyalty_update_restaurant_loyalty_config", domain: "loyalty", actionModule: "actions/loyalty.ts", operation: "updateRestaurantLoyaltyConfigAction", permission: "loyalty.manage", risk: "high" },
  { id: "marketing_create_holiday_package", domain: "marketing", actionModule: "actions/marketing/holiday-packages.ts", operation: "createHolidayPackageAction", permission: "orders.manage", risk: "high" },
  { id: "meal_plans_create_meal_plan", domain: "meal_plans", actionModule: "actions/meal-plans.ts", operation: "createMealPlanAction", permission: "production.manage", risk: "high" },
  { id: "meal_plans_create_meal_plan_form", domain: "meal_plans", actionModule: "actions/meal-plans.ts", operation: "createMealPlanFormAction", permission: "production.manage", risk: "high" },
  { id: "notification_rules_toggle_notification_rule", domain: "notification_rules", actionModule: "actions/notification-rules.ts", operation: "toggleNotificationRuleAction", permission: "orders.manage", risk: "high" },
  { id: "notification_rules_seed_notification_rules", domain: "notification_rules", actionModule: "actions/notification-rules.ts", operation: "seedNotificationRulesAction", permission: "orders.manage", risk: "high" },
  { id: "notifications_center_send_test_email", domain: "notifications_center", actionModule: "actions/notifications-center.ts", operation: "sendTestEmailAction", permission: "orders.manage", risk: "high" },
  { id: "notifications_center_retry_notification", domain: "notifications_center", actionModule: "actions/notifications-center.ts", operation: "retryNotificationAction", permission: "orders.manage", risk: "high" },
  { id: "nutrition_label_settings_update_nutrition_packing_gates", domain: "nutrition_label_settings", actionModule: "actions/nutrition-label-settings.ts", operation: "updateNutritionPackingGatesAction", permission: "workspace.settings", risk: "critical" },
  { id: "nutrition_label_settings_update_storefront_label_visibility", domain: "nutrition_label_settings", actionModule: "actions/nutrition-label-settings.ts", operation: "updateStorefrontLabelVisibilityAction", permission: "workspace.settings", risk: "critical" },
  { id: "nutrition_label_verification_verify_nutrition_profile", domain: "nutrition_label_verification", actionModule: "actions/nutrition-label-verification.ts", operation: "verifyNutritionProfileAction", permission: "products.edit", risk: "high" },
  { id: "nutrition_label_verification_set_nutrition_verification_status", domain: "nutrition_label_verification", actionModule: "actions/nutrition-label-verification.ts", operation: "setNutritionVerificationStatusAction", permission: "products.edit", risk: "high" },
  { id: "nutrition_profile_upsert_nutrition_profile", domain: "nutrition_profile", actionModule: "actions/nutrition-profile.ts", operation: "upsertNutritionProfileAction", permission: "products.edit", risk: "high" },
  { id: "nutrition_profile_upsert_nutrition_profile_form", domain: "nutrition_profile", actionModule: "actions/nutrition-profile.ts", operation: "upsertNutritionProfileFormAction", permission: "products.edit", risk: "high" },
  { id: "operations_create_operations_checklist", domain: "operations", actionModule: "actions/operations.ts", operation: "createOperationsChecklistAction", permission: "workspace.view", risk: "low" },
  { id: "operations_start_operations_audit", domain: "operations", actionModule: "actions/operations.ts", operation: "startOperationsAuditAction", permission: "orders.manage", risk: "high" },
  { id: "order_creation_create_order_via_center", domain: "order_creation", actionModule: "actions/order-creation.ts", operation: "createOrderViaCenterAction", permission: "orders.manage", risk: "high" },
  { id: "outbound_webhooks_load_outbound_webhooks_hub_data", domain: "outbound_webhooks", actionModule: "actions/outbound-webhooks.ts", operation: "loadOutboundWebhooksHubDataAction", permission: "workspace.view", risk: "low" },
  { id: "outbound_webhooks_create_outbound_webhook_subscription", domain: "outbound_webhooks", actionModule: "actions/outbound-webhooks.ts", operation: "createOutboundWebhookSubscriptionAction", permission: "integrations.manage", risk: "high" },
  { id: "packing_verification_get_verification_session_detail", domain: "packing_verification", actionModule: "actions/packing-verification.ts", operation: "getVerificationSessionDetailAction", permission: "workspace.view", risk: "low" },
  { id: "packing_verification_start_verification_session", domain: "packing_verification", actionModule: "actions/packing-verification.ts", operation: "startVerificationSessionAction", permission: "packing.manage", risk: "high" },
  { id: "packing_verify_lookup_order_by_pack_token", domain: "packing_verify", actionModule: "actions/packing-verify.ts", operation: "lookupOrderByPackTokenAction", permission: "packing.manage", risk: "high" },
  { id: "packing_verify_log_packing_event", domain: "packing_verify", actionModule: "actions/packing-verify.ts", operation: "logPackingEventAction", permission: "packing.manage", risk: "high" },
  { id: "packing_generate_packing_queue", domain: "packing", actionModule: "actions/packing.ts", operation: "generatePackingQueueAction", permission: "packing.manage", risk: "high" },
  { id: "packing_update_packing_task_status", domain: "packing", actionModule: "actions/packing.ts", operation: "updatePackingTaskStatusAction", permission: "packing.manage", risk: "high" },
  { id: "partner_app_register_submit_partner_app_registration", domain: "partner_app_register", actionModule: "actions/partner-app-register.ts", operation: "submitPartnerAppRegistrationAction", permission: "integrations.manage", risk: "high" },
  { id: "partner_app_review_approve_partner_app_review", domain: "partner_app_review", actionModule: "actions/partner-app-review.ts", operation: "approvePartnerAppReviewAction", permission: "workspace.view", risk: "low" },
  { id: "partner_app_review_reject_partner_app_review", domain: "partner_app_review", actionModule: "actions/partner-app-review.ts", operation: "rejectPartnerAppReviewAction", permission: "workspace.view", risk: "low" },
  { id: "partner_billing_sync_partner_billing_meters", domain: "partner_billing", actionModule: "actions/partner-billing.ts", operation: "syncPartnerBillingMetersAction", permission: "billing.manage", risk: "critical" },
  { id: "partner_billing_generate_partner_billing_statement", domain: "partner_billing", actionModule: "actions/partner-billing.ts", operation: "generatePartnerBillingStatementAction", permission: "billing.manage", risk: "critical" },
  { id: "partner_oauth_load_partner_o_auth_hub_data", domain: "partner_oauth", actionModule: "actions/partner-oauth.ts", operation: "loadPartnerOAuthHubDataAction", permission: "workspace.view", risk: "low" },
  { id: "partner_oauth_approve_partner_o_auth_consent", domain: "partner_oauth", actionModule: "actions/partner-oauth.ts", operation: "approvePartnerOAuthConsentAction", permission: "integrations.manage", risk: "high" },
  { id: "partner_stripe_connect_start_partner_stripe_connect", domain: "partner_stripe_connect", actionModule: "actions/partner-stripe-connect.ts", operation: "startPartnerStripeConnectAction", permission: "integrations.manage", risk: "high" },
  { id: "platform_impersonation_start_impersonation_form", domain: "platform_impersonation", actionModule: "actions/platform-impersonation.ts", operation: "startImpersonationFormAction", permission: "orders.manage", risk: "high" },
  { id: "platform_pilot_enrollments_set_workspace_pilot_enrollment", domain: "platform_pilot_enrollments", actionModule: "actions/platform-pilot-enrollments.ts", operation: "setWorkspacePilotEnrollmentAction", permission: "orders.manage", risk: "high" },
  { id: "platform_pilot_enrollments_clear_workspace_pilot_enrollment", domain: "platform_pilot_enrollments", actionModule: "actions/platform-pilot-enrollments.ts", operation: "clearWorkspacePilotEnrollmentAction", permission: "orders.manage", risk: "high" },
  { id: "platform_support_session_start_platform_support_session", domain: "platform_support_session", actionModule: "actions/platform-support-session.ts", operation: "startPlatformSupportSessionAction", permission: "orders.manage", risk: "high" },
  { id: "platform_support_session_end_platform_support_session", domain: "platform_support_session", actionModule: "actions/platform-support-session.ts", operation: "endPlatformSupportSessionAction", permission: "orders.manage", risk: "high" },
  { id: "platform_support_add_platform_support_internal_comment", domain: "platform_support", actionModule: "actions/platform-support.ts", operation: "addPlatformSupportInternalCommentAction", permission: "orders.manage", risk: "high" },
  { id: "platform_support_add_platform_support_customer_reply", domain: "platform_support", actionModule: "actions/platform-support.ts", operation: "addPlatformSupportCustomerReplyAction", permission: "orders.manage", risk: "high" },
  { id: "playbooks_ensure_system_playbooks", domain: "playbooks", actionModule: "actions/playbooks.ts", operation: "ensureSystemPlaybooksAction", permission: "playbooks.manage", risk: "high" },
  { id: "playbooks_start_run", domain: "playbooks", actionModule: "actions/playbooks.ts", operation: "startRunAction", permission: "playbooks.manage", risk: "high" },
  { id: "pos_terminal_customers_pos_search_kitchen_customers", domain: "pos_terminal_customers", actionModule: "actions/pos-terminal-customers.ts", operation: "posSearchKitchenCustomersAction", permission: "pos.checkout", risk: "medium" },
  { id: "pos_terminal_customers_pos_quick_create_kitchen_customer", domain: "pos_terminal_customers", actionModule: "actions/pos-terminal-customers.ts", operation: "posQuickCreateKitchenCustomerAction", permission: "pos.checkout", risk: "medium" },
  { id: "pos_pos_checkout", domain: "pos", actionModule: "actions/pos.ts", operation: "posCheckoutAction", permission: "pos.checkout", risk: "medium" },
  { id: "pos_pos_create_register", domain: "pos", actionModule: "actions/pos.ts", operation: "posCreateRegisterAction", permission: "pos.checkout", risk: "medium" },
  { id: "pos_assign_tab_item_participant", domain: "pos", actionModule: "actions/pos/bill-split.ts", operation: "assignTabItemParticipantAction", permission: "pos.checkout", risk: "medium" },
  { id: "pos_clear_tab_split_assignments", domain: "pos", actionModule: "actions/pos/bill-split.ts", operation: "clearTabSplitAssignmentsAction", permission: "pos.checkout", risk: "medium" },
  { id: "pos_create_tab", domain: "pos", actionModule: "actions/pos/tabs.ts", operation: "createTabAction", permission: "pos.checkout", risk: "medium" },
  { id: "pos_add_item_to_tab", domain: "pos", actionModule: "actions/pos/tabs.ts", operation: "addItemToTabAction", permission: "pos.checkout", risk: "medium" },
  { id: "product_categories_create_custom_category", domain: "product_categories", actionModule: "actions/product-categories.ts", operation: "createCustomCategoryAction", permission: "orders.manage", risk: "high" },
  { id: "product_mapping_create_mapping_suggestion", domain: "product_mapping", actionModule: "actions/product-mapping.ts", operation: "createMappingSuggestionAction", permission: "orders.manage", risk: "high" },
  { id: "product_mapping_approve_mapping", domain: "product_mapping", actionModule: "actions/product-mapping.ts", operation: "approveMappingAction", permission: "orders.manage", risk: "high" },
  { id: "production_calendar_create_plan_task", domain: "production_calendar", actionModule: "actions/production-calendar.ts", operation: "createPlanTaskAction", permission: "production.manage", risk: "high" },
  { id: "production_calendar_move_plan_task", domain: "production_calendar", actionModule: "actions/production-calendar.ts", operation: "movePlanTaskAction", permission: "production.manage", risk: "high" },
  { id: "production_daily_queue_fetch_today_queue", domain: "production_daily_queue", actionModule: "actions/production-daily-queue.ts", operation: "fetchTodayQueueAction", permission: "production.manage", risk: "high" },
  { id: "production_incidents_update_production_incident_workflow_form", domain: "production_incidents", actionModule: "actions/production-incidents.ts", operation: "updateProductionIncidentWorkflowFormAction", permission: "production.manage", risk: "high" },
  { id: "production_incidents_update_production_incident_review_form", domain: "production_incidents", actionModule: "actions/production-incidents.ts", operation: "updateProductionIncidentReviewFormAction", permission: "production.manage", risk: "high" },
  { id: "production_generate_production_menu_prep_form", domain: "production", actionModule: "actions/production.ts", operation: "generateProductionMenuPrepFormAction", permission: "production.manage", risk: "high" },
  { id: "production_generate_production_orders_form", domain: "production", actionModule: "actions/production.ts", operation: "generateProductionOrdersFormAction", permission: "production.manage", risk: "high" },
  { id: "products_update_product_image_form", domain: "products", actionModule: "actions/products.ts", operation: "updateProductImageFormAction", permission: "products.edit", risk: "high" },
  { id: "purchasing_bulk_update_prices", domain: "purchasing", actionModule: "actions/purchasing/bulk-price.ts", operation: "bulkUpdatePricesAction", permission: "production.manage", risk: "high" },
  { id: "purchasing_undo_bulk_prices", domain: "purchasing", actionModule: "actions/purchasing/bulk-price.ts", operation: "undoBulkPricesAction", permission: "production.manage", risk: "high" },
  { id: "reports_save_report", domain: "reports", actionModule: "actions/reports.ts", operation: "saveReportAction", permission: "orders.manage", risk: "high" },
  { id: "reports_delete_saved_report", domain: "reports", actionModule: "actions/reports.ts", operation: "deleteSavedReportAction", permission: "workspace.settings", risk: "critical" },
  { id: "restaurant_update_table_status", domain: "restaurant", actionModule: "actions/restaurant/tables.ts", operation: "updateTableStatusAction", permission: "pos.access", risk: "medium" },
  { id: "settings_save_account_notification_prefs", domain: "settings", actionModule: "actions/settings/account-notifications.ts", operation: "saveAccountNotificationPrefsAction", permission: "workspace.settings", risk: "critical" },
  { id: "settings_upload_avatar", domain: "settings", actionModule: "actions/settings/avatar.ts", operation: "uploadAvatarAction", permission: "workspace.view", risk: "low" },
  { id: "settings_remove_avatar", domain: "settings", actionModule: "actions/settings/avatar.ts", operation: "removeAvatarAction", permission: "workspace.settings", risk: "critical" },
  { id: "settings_change_email", domain: "settings", actionModule: "actions/settings/email.ts", operation: "changeEmailAction", permission: "workspace.settings", risk: "critical" },
  { id: "settings_change_password", domain: "settings", actionModule: "actions/settings/password.ts", operation: "changePasswordAction", permission: "workspace.settings", risk: "critical" },
  { id: "settings_update_profile", domain: "settings", actionModule: "actions/settings/profile.ts", operation: "updateProfileAction", permission: "workspace.settings", risk: "critical" },
  { id: "shopify_b2b_ar_dashboard_bulk_send_b2b_ar_reminders", domain: "shopify_b2b_ar_dashboard", actionModule: "actions/shopify-b2b-ar-dashboard.ts", operation: "bulkSendB2bArRemindersAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_ar_dashboard_bulk_mint_b2b_ar_pay_links", domain: "shopify_b2b_ar_dashboard", actionModule: "actions/shopify-b2b-ar-dashboard.ts", operation: "bulkMintB2bArPayLinksAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_collector_queue_update_b2b_collector_task_status", domain: "shopify_b2b_collector_queue", actionModule: "actions/shopify-b2b-collector-queue.ts", operation: "updateB2bCollectorTaskStatusAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_collector_queue_set_b2b_collector_sla", domain: "shopify_b2b_collector_queue", actionModule: "actions/shopify-b2b-collector-queue.ts", operation: "setB2bCollectorSlaAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_consolidated_pay_mint_b2b_consolidated_pay_link", domain: "shopify_b2b_consolidated_pay", actionModule: "actions/shopify-b2b-consolidated-pay.ts", operation: "mintB2bConsolidatedPayLinkAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_dunning_preview_b2b_dunning_digest", domain: "shopify_b2b_dunning", actionModule: "actions/shopify-b2b-dunning.ts", operation: "previewB2bDunningDigestAction", permission: "workspace.view", risk: "low" },
  { id: "shopify_b2b_dunning_run_b2b_dunning_now", domain: "shopify_b2b_dunning", actionModule: "actions/shopify-b2b-dunning.ts", operation: "runB2bDunningNowAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_invoice_mark_b2b_invoice_paid", domain: "shopify_b2b_invoice", actionModule: "actions/shopify-b2b-invoice.ts", operation: "markB2bInvoicePaidAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_invoice_mark_b2b_invoice_paid_form", domain: "shopify_b2b_invoice", actionModule: "actions/shopify-b2b-invoice.ts", operation: "markB2bInvoicePaidFormAction", permission: "integrations.manage", risk: "high" },
  { id: "shopify_b2b_pay_portal_get_b2b_invoice_pay_link", domain: "shopify_b2b_pay_portal", actionModule: "actions/shopify-b2b-pay-portal.ts", operation: "getB2bInvoicePayLinkAction", permission: "workspace.view", risk: "low" },
  { id: "shopify_markets_discover_shopify_markets", domain: "shopify_markets", actionModule: "actions/shopify-markets.ts", operation: "discoverShopifyMarketsAction", permission: "workspace.view", risk: "low" },
  { id: "shopify_markets_import_shopify_market_prices", domain: "shopify_markets", actionModule: "actions/shopify-markets.ts", operation: "importShopifyMarketPricesAction", permission: "integrations.manage", risk: "high" },
  { id: "staff_member_create_staff_member", domain: "staff_member", actionModule: "actions/staff-member.ts", operation: "createStaffMemberAction", permission: "staff.manage", risk: "high" },
  { id: "staff_member_create_staff_member_form", domain: "staff_member", actionModule: "actions/staff-member.ts", operation: "createStaffMemberFormAction", permission: "staff.manage", risk: "high" },
  { id: "staff_create_staff", domain: "staff", actionModule: "actions/staff.ts", operation: "createStaffAction", permission: "staff.manage", risk: "high" },
  { id: "staff_update_staff", domain: "staff", actionModule: "actions/staff.ts", operation: "updateStaffAction", permission: "staff.manage", risk: "high" },
  { id: "storefront_advanced_upsert_storefront_redirect", domain: "storefront_advanced", actionModule: "actions/storefront-advanced.ts", operation: "upsertStorefrontRedirectAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_advanced_delete_storefront_redirect", domain: "storefront_advanced", actionModule: "actions/storefront-advanced.ts", operation: "deleteStorefrontRedirectAction", permission: "workspace.settings", risk: "critical" },
  { id: "storefront_blackout_create_storefront_blackout_date_form", domain: "storefront_blackout", actionModule: "actions/storefront-blackout.ts", operation: "createStorefrontBlackoutDateFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_blackout_delete_storefront_blackout_date_form", domain: "storefront_blackout", actionModule: "actions/storefront-blackout.ts", operation: "deleteStorefrontBlackoutDateFormAction", permission: "workspace.settings", risk: "critical" },
  { id: "storefront_catalog_admin_upsert_storefront_variant", domain: "storefront_catalog_admin", actionModule: "actions/storefront-catalog-admin.ts", operation: "upsertStorefrontVariantAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_catalog_admin_delete_storefront_variant", domain: "storefront_catalog_admin", actionModule: "actions/storefront-catalog-admin.ts", operation: "deleteStorefrontVariantAction", permission: "workspace.settings", risk: "critical" },
  { id: "storefront_discounts_create_storefront_discount", domain: "storefront_discounts", actionModule: "actions/storefront-discounts.ts", operation: "createStorefrontDiscountAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_discounts_toggle_storefront_discount", domain: "storefront_discounts", actionModule: "actions/storefront-discounts.ts", operation: "toggleStorefrontDiscountAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_domains_verify_storefront_domain_dns", domain: "storefront_domains", actionModule: "actions/storefront-domains.ts", operation: "verifyStorefrontDomainDnsAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_domains_refresh_storefront_domain_status", domain: "storefront_domains", actionModule: "actions/storefront-domains.ts", operation: "refreshStorefrontDomainStatusAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_experiment_settings_update_storefront_experiment_ops_settings", domain: "storefront_experiment_settings", actionModule: "actions/storefront-experiment-settings.ts", operation: "updateStorefrontExperimentOpsSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_forms_create_storefront_form", domain: "storefront_forms", actionModule: "actions/storefront-forms.ts", operation: "createStorefrontFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_forms_update_storefront_form", domain: "storefront_forms", actionModule: "actions/storefront-forms.ts", operation: "updateStorefrontFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_markets_update_storefront_markets", domain: "storefront_markets", actionModule: "actions/storefront-markets.ts", operation: "updateStorefrontMarketsAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_markets_seed_default_market", domain: "storefront_markets", actionModule: "actions/storefront-markets.ts", operation: "seedDefaultMarketAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_media_upload_storefront_media_form", domain: "storefront_media", actionModule: "actions/storefront-media.ts", operation: "uploadStorefrontMediaFormAction", permission: "workspace.view", risk: "low" },
  { id: "storefront_media_delete_storefront_media_form", domain: "storefront_media", actionModule: "actions/storefront-media.ts", operation: "deleteStorefrontMediaFormAction", permission: "workspace.settings", risk: "critical" },
  { id: "storefront_multi_store_set_active_admin_storefront", domain: "storefront_multi_store", actionModule: "actions/storefront-multi-store.ts", operation: "setActiveAdminStorefrontAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_multi_store_create_additional_storefront", domain: "storefront_multi_store", actionModule: "actions/storefront-multi-store.ts", operation: "createAdditionalStorefrontAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_navigation_update_storefront_navigation_settings_form", domain: "storefront_navigation", actionModule: "actions/storefront-navigation.ts", operation: "updateStorefrontNavigationSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_navigation_update_storefront_footer_settings_form", domain: "storefront_navigation", actionModule: "actions/storefront-navigation.ts", operation: "updateStorefrontFooterSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_pages_create_storefront_page_form", domain: "storefront_pages", actionModule: "actions/storefront-pages.ts", operation: "createStorefrontPageFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_pages_update_storefront_page_details_form", domain: "storefront_pages", actionModule: "actions/storefront-pages.ts", operation: "updateStorefrontPageDetailsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_pillar_settings_update_storefront_theme_settings_form", domain: "storefront_pillar_settings", actionModule: "actions/storefront-pillar-settings.ts", operation: "updateStorefrontThemeSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_pillar_settings_update_storefront_fulfillment_settings_form", domain: "storefront_pillar_settings", actionModule: "actions/storefront-pillar-settings.ts", operation: "updateStorefrontFulfillmentSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_product_public_update_storefront_product_fields_form", domain: "storefront_product_public", actionModule: "actions/storefront-product-public.ts", operation: "updateStorefrontProductFieldsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_regional_update_storefront_regional_settings_form", domain: "storefront_regional", actionModule: "actions/storefront-regional.ts", operation: "updateStorefrontRegionalSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_reservations_get_reservation_availability", domain: "storefront_reservations", actionModule: "actions/storefront-reservations.ts", operation: "getReservationAvailabilityAction", permission: "workspace.view", risk: "low" },
  { id: "storefront_reservations_create_reservation", domain: "storefront_reservations", actionModule: "actions/storefront-reservations.ts", operation: "createReservationAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_settings_upsert_storefront_settings_form", domain: "storefront_settings", actionModule: "actions/storefront-settings.ts", operation: "upsertStorefrontSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_settings_update_storefront_business_settings_form", domain: "storefront_settings", actionModule: "actions/storefront-settings.ts", operation: "updateStorefrontBusinessSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_stripe_connect_start_storefront_stripe_connect", domain: "storefront_stripe_connect", actionModule: "actions/storefront-stripe-connect.ts", operation: "startStorefrontStripeConnectAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_tax_settings_save_storefront_tax_settings_form", domain: "storefront_tax_settings", actionModule: "actions/storefront-tax-settings.ts", operation: "saveStorefrontTaxSettingsFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_tax_settings_apply_storefront_tax_preset_form", domain: "storefront_tax_settings", actionModule: "actions/storefront-tax-settings.ts", operation: "applyStorefrontTaxPresetFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_team_invite_invite_storefront_team_member", domain: "storefront_team_invite", actionModule: "actions/storefront-team-invite.ts", operation: "inviteStorefrontTeamMemberAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_team_invite_cancel_storefront_team_invite", domain: "storefront_team_invite", actionModule: "actions/storefront-team-invite.ts", operation: "cancelStorefrontTeamInviteAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_team_update_storefront_staff_access", domain: "storefront_team", actionModule: "actions/storefront-team.ts", operation: "updateStorefrontStaffAccessAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_theme_experiment_retry_theme_experiment_edge_sync", domain: "storefront_theme_experiment", actionModule: "actions/storefront-theme-experiment.ts", operation: "retryThemeExperimentEdgeSyncAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_theme_experiment_retry_theme_experiment_edge_sync_form", domain: "storefront_theme_experiment", actionModule: "actions/storefront-theme-experiment.ts", operation: "retryThemeExperimentEdgeSyncFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_theme_preset_apply_storefront_theme_preset_form", domain: "storefront_theme_preset", actionModule: "actions/storefront-theme-preset.ts", operation: "applyStorefrontThemePresetFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_theme_publish_publish_storefront_theme_form", domain: "storefront_theme_publish", actionModule: "actions/storefront-theme-publish.ts", operation: "publishStorefrontThemeFormAction", permission: "storefront.publish", risk: "medium" },
  { id: "storefront_webhook_delivery_redeliver_page_publish_webhook_form", domain: "storefront_webhook_delivery", actionModule: "actions/storefront-webhook-delivery.ts", operation: "redeliverPagePublishWebhookFormAction", permission: "storefront.publish", risk: "medium" },
  { id: "storefront_workspace_link_storefront_to_workspace", domain: "storefront_workspace", actionModule: "actions/storefront-workspace.ts", operation: "linkStorefrontToWorkspaceAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_workspace_link_storefront_to_brand", domain: "storefront_workspace", actionModule: "actions/storefront-workspace.ts", operation: "linkStorefrontToBrandAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_lookup_gift_card_balance", domain: "storefront", actionModule: "actions/storefront/gift-cards-public.ts", operation: "lookupGiftCardBalanceAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_issue_gift_card_form", domain: "storefront", actionModule: "actions/storefront/gift-cards.ts", operation: "issueGiftCardFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_create_pickup_window_form", domain: "storefront", actionModule: "actions/storefront/pickup-windows.ts", operation: "createPickupWindowFormAction", permission: "storefront.manage", risk: "high" },
  { id: "storefront_create_pickup_window", domain: "storefront", actionModule: "actions/storefront/pickup-windows.ts", operation: "createPickupWindowAction", permission: "storefront.manage", risk: "high" },
  { id: "support_tickets_escalate_support_ticket", domain: "support_tickets", actionModule: "actions/support-tickets.ts", operation: "escalateSupportTicketAction", permission: "orders.manage", risk: "high" },
  { id: "team_post_team_communication", domain: "team", actionModule: "actions/team/communication.ts", operation: "postTeamCommunicationAction", permission: "orders.manage", risk: "high" },
  { id: "team_mark_team_communication_read", domain: "team", actionModule: "actions/team/communication.ts", operation: "markTeamCommunicationReadAction", permission: "workspace.view", risk: "low" },
  { id: "templates_preview_template", domain: "templates", actionModule: "actions/templates.ts", operation: "previewTemplateAction", permission: "workspace.view", risk: "low" },
  { id: "templates_apply_template", domain: "templates", actionModule: "actions/templates.ts", operation: "applyTemplateAction", permission: "orders.manage", risk: "high" },
  { id: "training_create_program", domain: "training", actionModule: "actions/training.ts", operation: "createProgramAction", permission: "training.manage", risk: "high" },
  { id: "training_assign_program", domain: "training", actionModule: "actions/training.ts", operation: "assignProgramAction", permission: "training.manage", risk: "high" },
  { id: "upload_upload_product_image", domain: "upload", actionModule: "actions/upload.ts", operation: "uploadProductImageAction", permission: "workspace.view", risk: "low" },
  { id: "upload_upload_business_logo", domain: "upload", actionModule: "actions/upload.ts", operation: "uploadBusinessLogoAction", permission: "workspace.view", risk: "low" },
  { id: "webhook_replay_replay_webhook_event", domain: "webhook_replay", actionModule: "actions/webhook-replay.ts", operation: "replayWebhookEventAction", permission: "orders.manage", risk: "high" },
  { id: "workspace_sso_load_workspace_sso_admin_view", domain: "workspace_sso", actionModule: "actions/workspace-sso.ts", operation: "loadWorkspaceSsoAdminViewAction", permission: "workspace.view", risk: "low" },
  { id: "workspace_sso_configure_workspace_sso_pilot", domain: "workspace_sso", actionModule: "actions/workspace-sso.ts", operation: "configureWorkspaceSsoPilotAction", permission: "orders.manage", risk: "high" },
] as const;

export function getActionMutationOperation(id: string): ActionMutationOperationEntry | undefined {
  return ACTION_MUTATION_OPERATIONS.find((e) => e.id === id);
}

export function listActionMutationsByDomain(domain: string): ActionMutationOperationEntry[] {
  return ACTION_MUTATION_OPERATIONS.filter((e) => e.domain === domain);
}
