import type { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  "workspace.view": "View workspace",
  "workspace.settings": "Manage workspace settings",
  "orders.manage": "Create and update orders",
  "orders.export": "Export order and fulfillment CSV data",
  "orders.void": "Void or cancel orders",
  "pos.access": "Access POS surfaces",
  "pos.checkout": "Complete POS checkout",
  "pos.discount.apply": "Apply POS discounts or comp sales",
  "pos.refund": "Refund POS transactions",
  "pos.void": "Void POS transactions",
  "pos.shift.open": "Open POS shifts",
  "pos.shift.close": "Close POS shifts",
  "pos.register.manage": "Manage POS registers",
  "pos.hardware.manage": "Manage POS hardware settings",
  "pos.manager.override": "Approve manager-only POS overrides",
  "products.edit": "Create and edit products",
  "payroll.view": "View and export payroll CSV data",
  "reports.read.operations": "View operational and production reports",
  "reports.read.financial": "View financial and margin reports",
  "reports.read.customer_pii": "View customer reports with contact details",
  "reports.read.audit": "View audit and compliance reports",
  "reports.export": "Export operational and financial report CSV data",
  "reports.saved.manage": "Save and manage pinned report views",
  "audit.export": "Export workspace audit log CSV data",
  "customers.read": "View CRM customers, segments, and workspace customer reports",
  "customers.manage": "Manage CRM customers and segments",
  "customers.export": "Export customer and guest CSV data",
  "loyalty.manage": "Configure loyalty program rules and redemptions",
  "giftcards.manage": "Issue and manage workspace gift cards",
  "production.manage": "Operate production boards",
  "kitchen.view": "View kitchen display tickets",
  "kitchen.bump": "Bump kitchen display tickets",
  "kitchen.recall": "Recall bumped kitchen tickets back to prep",
  "kitchen.configure": "Configure kitchen display filters and layout",
  "kitchen.expo.manage": "Expo handoff and cross-station kitchen coordination",
  "packing.manage": "Operate packing",
  "routes.manage": "Plan and dispatch routes",
  "billing.view": "View billing and subscription status",
  "billing.manage": "Manage billing",
  "integrations.read": "View sales channel integrations and health",
  "integrations.manage": "Connect and manage sales channels",
  "storefront.read": "View storefront builder and settings",
  "storefront.manage": "Edit storefront drafts and configuration",
  "storefront.publish": "Publish storefront theme and pages live",
  "storefront.media.manage": "Upload and delete storefront media assets",
  "staff.manage": "Invite and manage staff",
  "schedule.manage": "Create and edit labor schedules",
  "timeclock.manage": "Clock staff in and out on the time clock",
  "training.manage": "Create programs, SOPs, assignments, and certifications",
  "training.participate": "Complete assigned training, quizzes, and simulations",
  "go-live.manage": "Create and operate launch readiness projects",
  "go-live.unlock": "Override critical launch blockers",
  "executive.insights.manage": "Resolve or dismiss executive dashboard insights",
  "playbooks.manage": "Create, edit, and archive custom playbooks",
  "playbooks.participate": "View playbooks and complete run steps",
  "templates.manage": "Apply or roll back workspace quick-start templates",
  "templates.participate": "Preview workspace templates and view application history",
  "growth.view": "View growth / beta surfaces",
  "growth.manage": "Manage growth CRM, outreach, and founder operations",
  "marketplace:read": "View marketplace catalog, products, and vendors",
  "marketplace:cart:write": "Add to cart and checkout marketplace orders",
  "marketplace:orders:read": "View marketplace purchase orders",
  "marketplace:orders:create": "Create marketplace purchase orders",
  "marketplace:orders:cancel": "Cancel marketplace purchase orders",
  "marketplace:recurring:manage": "Create and edit recurring marketplace orders",
  "marketplace:reviews:write": "Write vendor reviews after completed orders",
  "marketplace:disputes:open": "Open marketplace order disputes",
  "vendor:cabinet:access": "Access vendor cabinet",
  "vendor:products:manage": "Create and manage vendor product catalog",
  "vendor:orders:read": "View incoming vendor orders",
  "vendor:orders:confirm": "Confirm or reject vendor orders",
  "vendor:orders:ship": "Mark vendor orders as shipped",
  "vendor:analytics:read": "View vendor analytics",
  "vendor:payouts:request": "Request vendor payouts",
  "vendor:messages:send": "Send messages to marketplace buyers",
  "marketplace:admin:moderate": "Approve or reject marketplace vendors and products",
  "marketplace:admin:disputes": "Resolve marketplace disputes",
  "marketplace:admin:featured": "Manage marketplace featured placements",
  "marketplace:admin:analytics": "View marketplace-wide analytics",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

export const MARKETPLACE_BUYER_PERMISSIONS = [
  "marketplace:read",
  "marketplace:cart:write",
  "marketplace:orders:read",
  "marketplace:orders:create",
  "marketplace:orders:cancel",
  "marketplace:recurring:manage",
  "marketplace:reviews:write",
  "marketplace:disputes:open",
] as const satisfies readonly PermissionKey[];

export const MARKETPLACE_VENDOR_PERMISSIONS = [
  "vendor:cabinet:access",
  "vendor:products:manage",
  "vendor:orders:read",
  "vendor:orders:confirm",
  "vendor:orders:ship",
  "vendor:analytics:read",
  "vendor:payouts:request",
  "vendor:messages:send",
] as const satisfies readonly PermissionKey[];

export const MARKETPLACE_ADMIN_PERMISSIONS = [
  "marketplace:admin:moderate",
  "marketplace:admin:disputes",
  "marketplace:admin:featured",
  "marketplace:admin:analytics",
] as const satisfies readonly PermissionKey[];

export const MARKETPLACE_PERMISSIONS = [
  ...MARKETPLACE_BUYER_PERMISSIONS,
  ...MARKETPLACE_VENDOR_PERMISSIONS,
  ...MARKETPLACE_ADMIN_PERMISSIONS,
] as const satisfies readonly PermissionKey[];

const OWNER_LIKE: readonly PermissionKey[] = [
  "workspace.view",
  "workspace.settings",
  "orders.manage",
  "orders.export",
  "orders.void",
  "pos.access",
  "pos.checkout",
  "pos.discount.apply",
  "pos.refund",
  "pos.void",
  "pos.shift.open",
  "pos.shift.close",
  "pos.register.manage",
  "pos.hardware.manage",
  "pos.manager.override",
  "products.edit",
  "payroll.view",
  "reports.read.operations",
  "reports.read.financial",
  "reports.read.customer_pii",
  "reports.read.audit",
  "reports.export",
  "reports.saved.manage",
  "audit.export",
  "customers.read",
  "customers.manage",
  "customers.export",
  "loyalty.manage",
  "giftcards.manage",
  "production.manage",
  "kitchen.view",
  "kitchen.bump",
  "kitchen.recall",
  "kitchen.configure",
  "kitchen.expo.manage",
  "packing.manage",
  "routes.manage",
  "billing.view",
  "billing.manage",
  "integrations.read",
  "integrations.manage",
  "storefront.read",
  "storefront.manage",
  "storefront.publish",
  "storefront.media.manage",
  "staff.manage",
  "schedule.manage",
  "timeclock.manage",
  "training.manage",
  "training.participate",
  "go-live.manage",
  "go-live.unlock",
  "executive.insights.manage",
  "playbooks.manage",
  "playbooks.participate",
  "templates.manage",
  "templates.participate",
  "growth.view",
  "growth.manage",
  ...MARKETPLACE_BUYER_PERMISSIONS,
];

const STAFF_OPS: readonly PermissionKey[] = [
  "workspace.view",
  "orders.manage",
  "pos.access",
  "pos.checkout",
  "production.manage",
  "kitchen.view",
  "kitchen.bump",
  "packing.manage",
  "routes.manage",
  "training.participate",
  "playbooks.participate",
  "marketplace:read",
  "marketplace:orders:read",
];

export function defaultPermissionsForWorkspaceRole(role: UserRole): Set<PermissionKey> {
  if (role === "OWNER") return new Set(OWNER_LIKE);
  return new Set(STAFF_OPS);
}
