import type { UserRole } from "@prisma/client";

export const PERMISSIONS = {
  "workspace.view": "View workspace",
  "workspace.settings": "Manage workspace settings",
  "orders.manage": "Create and update orders",
  "orders.export": "Export order and fulfillment CSV data",
  "orders.void": "Void or cancel orders",
  "pos.access": "Access POS surfaces",
  "pos.checkout": "Complete POS checkout",
  "pos.discount.apply": "Apply POS discounts or comp sales",
  "pos.refund": "Refund POS transactions",
  "pos.void": "Void POS transactions",
  "pos.shift.open": "Open POS shifts",
  "pos.shift.close": "Close POS shifts",
  "pos.register.manage": "Manage POS registers",
  "pos.hardware.manage": "Manage POS hardware settings",
  "pos.manager.override": "Approve manager-only POS overrides",
  "products.edit": "Create and edit products",
  "payroll.view": "View and export payroll CSV data",
  "reports.read.operations": "View operational and production reports",
  "reports.read.financial": "View financial and margin reports",
  "reports.read.customer_pii": "View customer reports with contact details",
  "reports.read.audit": "View audit and compliance reports",
  "reports.export": "Export operational and financial report CSV data",
  "reports.saved.manage": "Save and manage pinned report views",
  "audit.export": "Export workspace audit log CSV data",
  "customers.manage": "Manage CRM customers and segments",
  "customers.export": "Export customer and guest CSV data",
  "production.manage": "Operate production boards",
  "kitchen.view": "View kitchen display tickets",
  "kitchen.bump": "Bump kitchen display tickets",
  "kitchen.recall": "Recall bumped kitchen tickets back to prep",
  "kitchen.configure": "Configure kitchen display filters and layout",
  "kitchen.expo.manage": "Expo handoff and cross-station kitchen coordination",
  "packing.manage": "Operate packing",
  "routes.manage": "Plan and dispatch routes",
  "billing.view": "View billing and subscription status",
  "billing.manage": "Manage billing",
  "integrations.read": "View sales channel integrations and health",
  "integrations.manage": "Connect and manage sales channels",
  "storefront.read": "View storefront builder and settings",
  "storefront.manage": "Edit storefront drafts and configuration",
  "storefront.publish": "Publish storefront theme and pages live",
  "storefront.media.manage": "Upload and delete storefront media assets",
  "staff.manage": "Invite and manage staff",
  "schedule.manage": "Create and edit labor schedules",
  "timeclock.manage": "Clock staff in and out on the time clock",
  "growth.view": "View growth / beta surfaces",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

const OWNER_LIKE: readonly PermissionKey[] = [
  "workspace.view",
  "workspace.settings",
  "orders.manage",
  "orders.export",
  "orders.void",
  "pos.access",
  "pos.checkout",
  "pos.discount.apply",
  "pos.refund",
  "pos.void",
  "pos.shift.open",
  "pos.shift.close",
  "pos.register.manage",
  "pos.hardware.manage",
  "pos.manager.override",
  "products.edit",
  "payroll.view",
  "reports.read.operations",
  "reports.read.financial",
  "reports.read.customer_pii",
  "reports.read.audit",
  "reports.export",
  "reports.saved.manage",
  "audit.export",
  "customers.manage",
  "customers.export",
  "production.manage",
  "kitchen.view",
  "kitchen.bump",
  "kitchen.recall",
  "kitchen.configure",
  "kitchen.expo.manage",
  "packing.manage",
  "routes.manage",
  "billing.view",
  "billing.manage",
  "integrations.read",
  "integrations.manage",
  "storefront.read",
  "storefront.manage",
  "storefront.publish",
  "storefront.media.manage",
  "staff.manage",
  "schedule.manage",
  "timeclock.manage",
  "growth.view",
];

const STAFF_OPS: readonly PermissionKey[] = [
  "workspace.view",
  "orders.manage",
  "pos.access",
  "pos.checkout",
  "production.manage",
  "kitchen.view",
  "kitchen.bump",
  "packing.manage",
  "routes.manage",
];

export function defaultPermissionsForWorkspaceRole(role: UserRole): Set<PermissionKey> {
  if (role === "OWNER") return new Set(OWNER_LIKE);
  return new Set(STAFF_OPS);
}
