import type { BusinessType, SubscriptionPlan } from "@prisma/client";

/**
 * Canonical module metadata for navigation, gates, settings, and business-mode logic.
 * Path rules stay compatible with `pathAllowedByModuleGate` / `navigationHrefDisabled`.
 */
export const MODULE_REGISTRY_ENTRIES = [
  {
    key: "dashboard",
    label: "Dashboard",
    description: "Workspace home, KPIs, and setup progress.",
    category: "today",
    pathPrefixes: ["/dashboard"],
    pathMatch: "exact" as const,
    tier: "core" as const,
    requiredPlan: null as SubscriptionPlan | null,
    requiredFeature: null as string | null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [] as const,
  },
  {
    key: "today",
    label: "Today",
    description: "Daily operations board — orders, prep, fulfillment, alerts.",
    category: "today",
    pathPrefixes: ["/dashboard/today"],
    tier: "core",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "orders",
    label: "Orders",
    description: "Order list, statuses, and customer detail.",
    category: "orders",
    pathPrefixes: ["/dashboard/orders"],
    tier: "core",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "order_hub",
    label: "Order hub",
    description: "Unified queue across channels and manual entry.",
    category: "orders",
    pathPrefixes: ["/dashboard/order-hub"],
    tier: "core",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "pos_terminal",
    label: "POS Terminal",
    description: "Touch-first counter sales connected to orders, production, and inventory signals.",
    category: "orders",
    pathPrefixes: ["/dashboard/pos"],
    tier: "core",
    requiredPlan: "PRO",
    requiredFeature: "pos_terminal",
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "calendar",
    label: "Calendar",
    description: "Prep dates, events, and fulfillment windows.",
    category: "orders",
    pathPrefixes: ["/dashboard/calendar"],
    tier: "core",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "menus",
    label: "Weekly menus",
    description: "Time-bound menus and preorder deadlines.",
    category: "menu",
    pathPrefixes: ["/dashboard/menus"],
    tier: "menu",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "brands",
    label: "Brands",
    description: "Ghost / multi-brand lanes and naming.",
    category: "menu",
    pathPrefixes: ["/dashboard/brands"],
    tier: "menu",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "products",
    label: "Menu items",
    description: "SKUs, pricing, dates, and channel visibility.",
    category: "menu",
    pathPrefixes: ["/dashboard/products"],
    tier: "menu",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "menu_planner",
    label: "Menu planner",
    description: "Planning drafts before publishing.",
    category: "menu",
    pathPrefixes: ["/dashboard/menu-planner"],
    tier: "menu",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "storefront",
    label: "Storefront",
    description: "Public site, pages, and checkout configuration.",
    category: "menu",
    pathPrefixes: ["/dashboard/storefront"],
    tier: "menu",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "integrations",
    label: "Sales channels",
    description: "POS / delivery connectors, health, and webhooks.",
    category: "menu",
    pathPrefixes: ["/dashboard/sales-channels", "/dashboard/integrations"],
    tier: "menu",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "production",
    label: "Kitchen production",
    description: "Prep and cook progress by item.",
    category: "kitchen",
    pathPrefixes: ["/dashboard/production"],
    tier: "kitchen",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "kitchen_screen",
    label: "Kitchen screen",
    description: "Line-friendly station view.",
    category: "kitchen",
    pathPrefixes: ["/dashboard/kitchen"],
    tier: "kitchen",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "packing",
    label: "Packing & labels",
    description: "Packing lists, labels, and scan verify.",
    category: "kitchen",
    pathPrefixes: ["/dashboard/packing"],
    tier: "kitchen",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "nutrition_labels",
    label: "Nutrition labels",
    description: "Nutrition panels where you attach compliant data.",
    category: "kitchen",
    pathPrefixes: ["/dashboard/nutrition-labels"],
    tier: "kitchen",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "ingredient_demand",
    label: "Ingredient demand",
    description: "Explode menus into ingredient stress signals.",
    category: "inventory",
    pathPrefixes: [
      "/dashboard/inventory/demand",
      "/dashboard/inventory/waste",
      "/dashboard/inventory/counts",
    ],
    tier: "inventory",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "purchasing",
    label: "Purchasing",
    description: "Orders to suppliers from demand signals.",
    category: "inventory",
    pathPrefixes: ["/dashboard/purchasing", "/dashboard/accounting"],
    tier: "inventory",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "marketplace",
    label: "Marketplace",
    description: "B2B HoReCa supplies, equipment, and services from verified vendors.",
    category: "inventory",
    pathPrefixes: ["/dashboard/marketplace"],
    tier: "inventory",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: true,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "costing",
    label: "Costing & margin",
    description: "Recipe economics and margin snapshots.",
    category: "inventory",
    pathPrefixes: ["/dashboard/costing"],
    tier: "inventory",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "import_export",
    label: "Import / export",
    description: "CSV and structured data movement.",
    category: "inventory",
    pathPrefixes: ["/dashboard/import-export"],
    tier: "inventory",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "routes",
    label: "Routes",
    description: "Delivery sequencing and driver handoff.",
    category: "fulfillment",
    pathPrefixes: ["/dashboard/routes"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "tasks",
    label: "Tasks",
    description: "Checklists and operational follow-ups.",
    category: "fulfillment",
    pathPrefixes: ["/dashboard/tasks"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "locations",
    label: "Locations",
    description: "Sites, cloud lanes, and address book.",
    category: "fulfillment",
    pathPrefixes: ["/dashboard/locations"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "staff",
    label: "Staff",
    description: "Team roster and role hygiene (workspace-level).",
    category: "fulfillment",
    pathPrefixes: ["/dashboard/staff", "/dashboard/staff/schedule"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "customers",
    label: "Customer CRM",
    description: "Guests, companies, and history.",
    category: "customers",
    pathPrefixes: ["/dashboard/customers", "/dashboard/referrals"],
    tier: "customers",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "marketing",
    label: "Marketing",
    description: "Email campaigns and lifecycle automations.",
    category: "customers",
    pathPrefixes: ["/dashboard/marketing"],
    tier: "customers",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "meal_subscriptions",
    label: "Meal plans",
    description: "Recurring meal programs and subscriber hygiene.",
    category: "customers",
    pathPrefixes: ["/dashboard/meal-subscriptions"],
    tier: "customers",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "catering",
    label: "Catering quotes",
    description: "Quotes, packages, and event follow-up.",
    category: "customers",
    pathPrefixes: ["/dashboard/catering"],
    tier: "customers",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "analytics",
    label: "Analytics",
    description: "Operational and sales analytics.",
    category: "insights",
    pathPrefixes: ["/dashboard/analytics"],
    tier: "insights",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "forecast",
    label: "Forecast",
    description: "Forward-looking production and demand views.",
    category: "insights",
    pathPrefixes: ["/dashboard/forecast"],
    tier: "insights",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "food_safety",
    label: "Food safety",
    description: "Temperature logs, checklists, and HACCP-style audits.",
    category: "ops",
    pathPrefixes: ["/dashboard/food-safety", "/dashboard/operations"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "reports",
    label: "Reports",
    description: "Exports and scheduled operational reports.",
    category: "insights",
    pathPrefixes: ["/dashboard/reports", "/dashboard/integrations/doordash"],
    tier: "insights",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "executive",
    label: "Executive",
    description: "Portfolio rollups for multi-brand operators.",
    category: "insights",
    pathPrefixes: ["/dashboard/executive"],
    tier: "insights",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "copilot",
    label: "AI copilot",
    description: "Assisted answers — verify before acting.",
    category: "insights",
    pathPrefixes: ["/dashboard/copilot"],
    tier: "insights",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: true,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "implementation",
    label: "Implementation",
    description: "Rollout milestones and enterprise handoff.",
    category: "ops",
    pathPrefixes: ["/dashboard/implementation"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "import_center",
    label: "Import center",
    description: "Guided imports and templates.",
    category: "ops",
    pathPrefixes: ["/dashboard/import-center"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "product_mapping",
    label: "Product mapping",
    description: "External SKUs to internal catalog.",
    category: "ops",
    pathPrefixes: ["/dashboard/product-mapping"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "go_live",
    label: "Go-live",
    description: "Launch checklist and test runs.",
    category: "ops",
    pathPrefixes: ["/dashboard/go-live"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "training",
    label: "Training",
    description: "Role-based enablement content.",
    category: "ops",
    pathPrefixes: ["/dashboard/training"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "playbooks",
    label: "Playbooks",
    description: "Repeatable operational runbooks.",
    category: "ops",
    pathPrefixes: ["/dashboard/playbooks"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "templates",
    label: "Quick-start templates",
    description: "Apply starter configuration and sample data safely.",
    category: "ops",
    pathPrefixes: ["/dashboard/templates"],
    tier: "ops",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "billing",
    label: "Billing",
    description: "Plan, invoices, and payment method.",
    category: "admin",
    pathPrefixes: ["/dashboard/billing"],
    tier: "admin",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "notifications",
    label: "Notifications",
    description: "Customer messages and alert rules.",
    category: "admin",
    pathPrefixes: ["/dashboard/notifications"],
    tier: "admin",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "settings",
    label: "Settings",
    description: "Workspace profile, modules, and preferences.",
    category: "admin",
    pathPrefixes: ["/dashboard/settings"],
    tier: "admin",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "audit_logs",
    label: "Audit logs",
    description: "Security-sensitive change history.",
    category: "admin",
    pathPrefixes: ["/dashboard/audit-logs", "/dashboard/security/audit-logs"],
    tier: "admin",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "partner",
    label: "Partner",
    description: "Partner workspace tools.",
    category: "internal",
    pathPrefixes: ["/dashboard/partner"],
    tier: "internal",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: true,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "support",
    label: "Support",
    description: "Help and ticket intake.",
    category: "internal",
    pathPrefixes: ["/dashboard/support"],
    tier: "internal",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "growth",
    label: "Growth",
    description: "Internal GTM and customer success consoles.",
    category: "internal",
    pathPrefixes: ["/dashboard/growth"],
    tier: "internal",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: true,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "developer",
    label: "Developer",
    description: "API keys, webhooks, and integration tooling.",
    category: "internal",
    pathPrefixes: ["/dashboard/developer"],
    tier: "internal",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: false,
    superAdminOnly: false,
    isBeta: false,
    isPlaceholder: false,
    dependencies: [],
  },
  {
    key: "beta_applications",
    label: "Beta program",
    description: "Early access applications, cohorts, and founder pipeline.",
    category: "internal",
    pathPrefixes: ["/dashboard/beta-applications"],
    tier: "internal",
    requiredPlan: null,
    requiredFeature: null,
    internalOnly: true,
    superAdminOnly: false,
    isBeta: true,
    isPlaceholder: false,
    dependencies: [],
  },
] as const;

export type ModuleRegistryEntry = (typeof MODULE_REGISTRY_ENTRIES)[number];
export type ModuleKey = ModuleRegistryEntry["key"];

/** Optional per-mode hints — omitted entry means module is neutral across modes. */
export type ModuleModeHints = {
  recommended?: readonly BusinessType[];
  optional?: readonly BusinessType[];
  hidden?: readonly BusinessType[];
};

export function moduleModeHints(key: ModuleKey): ModuleModeHints | undefined {
  const hints: Partial<Record<ModuleKey, ModuleModeHints>> = {
    meal_subscriptions: {
      recommended: ["MEAL_PREP"],
      optional: ["CATERING", "BAKERY"],
      hidden: ["RESTAURANT", "CAFE", "BAR", "GHOST_KITCHEN", "CLOUD_KITCHEN", "MULTI_BRAND"],
    },
    nutrition_labels: {
      recommended: ["MEAL_PREP", "BAKERY"],
      optional: ["CATERING"],
      hidden: ["RESTAURANT", "CAFE", "BAR"],
    },
    executive: {
      recommended: ["MULTI_BRAND", "GHOST_KITCHEN", "CLOUD_KITCHEN"],
      optional: ["CATERING", "MEAL_PREP"],
    },
    brands: {
      recommended: ["GHOST_KITCHEN", "CLOUD_KITCHEN", "MULTI_BRAND"],
      optional: ["RESTAURANT", "MEAL_PREP"],
    },
    catering: {
      recommended: ["CATERING", "BAR"],
      optional: ["RESTAURANT", "MEAL_PREP"],
    },
    routes: {
      recommended: ["MEAL_PREP", "CATERING", "BAKERY"],
      optional: ["RESTAURANT", "GHOST_KITCHEN"],
    },
  };
  return hints[key];
}

export function moduleEntry(key: ModuleKey): ModuleRegistryEntry | undefined {
  return MODULE_REGISTRY_ENTRIES.find((e) => e.key === key);
}

export function hrefToModuleKeys(href: string): ModuleKey[] {
  const h = href.endsWith("/") && href.length > 1 ? href.slice(0, -1) : href;
  const keys: ModuleKey[] = [];
  for (const e of MODULE_REGISTRY_ENTRIES) {
    const exact = (e as { pathMatch?: "prefix" | "exact" }).pathMatch === "exact";
    for (const pre of e.pathPrefixes) {
      if (exact) {
        if (h === pre) keys.push(e.key);
      } else if (h === pre || h.startsWith(`${pre}/`)) {
        keys.push(e.key);
      }
    }
  }
  return keys;
}
