/** Human labels for `BusinessModeExperience.defaultTodayWidget` ids (Today Board focus). */
const LABELS: Record<string, string> = {
  priority_actions: "Today's priority actions",
  orders_attention: "Orders needing attention",
  prep_status: "Production / prep status",
  packing: "Packing & labels",
  routes: "Routes & delivery",
  nutrition_tasks: "Nutrition label tasks",
  events_today: "Upcoming events today",
  quotes_followup: "Quote follow-ups",
  production_timeline: "Event production timeline",
  delivery_setup: "Delivery & setup tasks",
  staff_tasks: "Staff tasks",
  channel_rush: "Channel rush & load",
  brand_load: "Brand production load",
  failed_syncs: "Failed syncs to review",
  multi_site_alerts: "Multi-site alerts",
  channel_orders: "Channel orders",
  brand_alerts: "Brand alerts",
  executive_summary: "Executive summary",
  integration_health: "Integration health",
  service_readiness: "Service readiness",
  takeout_delivery: "Takeout & delivery",
  prep_list: "Prep list",
  shortages: "Ingredient shortages",
  morning_prep: "Morning prep",
  specials: "Daily specials",
  pickup_orders: "Pickup orders",
  supplier_reminders: "Supplier reminders",
  low_stock: "Low stock",
  bar_prep: "Bar prep",
  beverage_stock: "Beverage stock",
  event_reminders: "Events & private bookings",
  margin_alerts: "Margin alerts",
  batch_plan: "Batch production plan",
  pickup_slots: "Preorder pickup slots",
  label_tasks: "Label tasks",
  allergen_notes: "Allergen & label notes",
  custom_orders: "Custom orders",
};

export function labelTodayWidget(id: string): string {
  return LABELS[id] ?? id.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
