import type { ReportDefinition, ReportKey } from "@/lib/reports/report-types";

/**
 * Single source of truth for what reports KitchenOS exposes.
 *
 * Every UI surface (library cards, generator page, CSV export endpoint,
 * permission gating) reads from this registry. To add a report:
 *   1. Add the key to `ReportKey` in `lib/reports/report-types.ts`.
 *   2. Add a `ReportDefinition` here.
 *   3. Add a runner in `services/reports/report-service.ts:reportRunners`.
 */
export const REPORT_REGISTRY: Record<ReportKey, ReportDefinition> = {
  executive_weekly_summary: {
    key: "executive_weekly_summary",
    title: "Executive weekly summary",
    description:
      "Revenue, orders, AOV, repeat customers, top products, top channels, production completion, packing accuracy, delivery performance and margin risks for the selected window.",
    category: "Executive",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["browser_print", "csv"],
    supportedFilters: ["dateRange", "brandId", "locationId"],
    columns: [
      { key: "metric", label: "Metric" },
      { key: "value", label: "Value", numeric: true },
      { key: "context", label: "Context" },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/executive_weekly_summary",
    status: "available",
    financial: true,
    tags: ["weekly", "owner", "executive"],
  },

  executive_monthly_summary: {
    key: "executive_monthly_summary",
    title: "Executive monthly summary",
    description:
      "Monthly revenue, growth vs. previous month, customer retention, margin signals, purchasing spend, and operational bottlenecks.",
    category: "Executive",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["browser_print", "csv"],
    supportedFilters: ["dateRange", "brandId", "locationId"],
    columns: [
      { key: "metric", label: "Metric" },
      { key: "value", label: "Value", numeric: true },
      { key: "context", label: "Context" },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/executive_monthly_summary",
    status: "available",
    financial: true,
    tags: ["monthly", "owner", "executive"],
  },

  revenue_report: {
    key: "revenue_report",
    title: "Revenue report",
    description:
      "Daily gross and net revenue for orders in the selected window. Cancelled orders excluded from net.",
    category: "Sales",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "brandId", "locationId", "channel", "fulfillmentType"],
    columns: [
      { key: "date", label: "Date" },
      { key: "orderCount", label: "Orders", numeric: true },
      { key: "grossRevenue", label: "Gross revenue", numeric: true, financial: true },
      { key: "netRevenue", label: "Net revenue", numeric: true, financial: true },
      { key: "cancelledRevenue", label: "Cancelled $", numeric: true, financial: true },
    ],
    legacyExportHref: "/api/export?type=orders",
    generatorRoute: "/dashboard/reports/revenue_report",
    status: "available",
    financial: true,
    tags: ["sales", "finance"],
  },

  orders_report: {
    key: "orders_report",
    title: "Orders report",
    description: "Order-level list with status, fulfillment, channel, and totals.",
    category: "Sales",
    businessModes: [],
    requiredPermission: "reports.read.operations",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "brandId", "locationId", "channel", "fulfillmentType", "status"],
    columns: [
      { key: "createdAt", label: "Created" },
      { key: "status", label: "Status" },
      { key: "fulfillmentType", label: "Fulfillment" },
      { key: "channel", label: "Channel" },
      { key: "customerName", label: "Customer" },
      { key: "total", label: "Total", numeric: true, financial: true },
    ],
    legacyExportHref: "/api/export?type=orders",
    generatorRoute: "/dashboard/reports/orders_report",
    status: "available",
    financial: false,
    tags: ["sales", "operations"],
  },

  sales_by_channel: {
    key: "sales_by_channel",
    title: "Sales by channel",
    description:
      "Revenue and order count grouped by channel (storefront, manual, external integrations).",
    category: "Sales",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "brandId", "locationId"],
    columns: [
      { key: "channel", label: "Channel" },
      { key: "orderCount", label: "Orders", numeric: true },
      { key: "revenue", label: "Revenue", numeric: true, financial: true },
      { key: "share", label: "Share", numeric: true },
    ],
    legacyExportHref: "/api/export?type=orders",
    generatorRoute: "/dashboard/reports/sales_by_channel",
    status: "available",
    financial: true,
    tags: ["channels"],
  },

  sales_by_product: {
    key: "sales_by_product",
    title: "Sales by product",
    description: "Quantity sold and revenue per product within the selected window.",
    category: "Sales",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "brandId", "locationId", "productId"],
    columns: [
      { key: "productTitle", label: "Product" },
      { key: "quantity", label: "Quantity", numeric: true },
      { key: "revenue", label: "Revenue", numeric: true, financial: true },
      { key: "orderCount", label: "Orders", numeric: true },
    ],
    legacyExportHref: "/api/export?type=products",
    generatorRoute: "/dashboard/reports/sales_by_product",
    status: "available",
    financial: true,
    tags: ["products", "sales"],
  },

  weekly_production: {
    key: "weekly_production",
    title: "Weekly production",
    description: "Production batches, quantities, and completion status for the window.",
    category: "Production",
    businessModes: [],
    requiredPermission: "reports.read.operations",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "brandId", "locationId"],
    columns: [
      { key: "title", label: "Batch" },
      { key: "status", label: "Status" },
      { key: "scheduledFor", label: "Scheduled" },
      { key: "targetQuantity", label: "Target qty", numeric: true },
      { key: "completedQuantity", label: "Completed qty", numeric: true },
    ],
    legacyExportHref: "/api/export?type=production",
    generatorRoute: "/dashboard/reports/weekly_production",
    status: "available",
    financial: false,
    tags: ["production", "kitchen"],
  },

  ingredient_demand: {
    key: "ingredient_demand",
    title: "Ingredient demand",
    description: "Ingredient demand lines from current demand runs.",
    category: "Inventory",
    businessModes: [],
    requiredPermission: "reports.read.operations",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "locationId"],
    columns: [
      { key: "ingredientName", label: "Ingredient" },
      { key: "requiredQuantity", label: "Required", numeric: true },
      { key: "onHandQuantity", label: "On hand", numeric: true },
      { key: "shortageQuantity", label: "Shortage", numeric: true },
      { key: "unit", label: "Unit" },
    ],
    legacyExportHref: "/api/export?type=inventory",
    generatorRoute: "/dashboard/reports/ingredient_demand",
    status: "available",
    financial: false,
    tags: ["inventory", "purchasing"],
  },

  inventory_shortage_report: {
    key: "inventory_shortage_report",
    title: "Inventory shortage report",
    description: "Open demand-run lines where required quantity exceeds on-hand stock.",
    category: "Inventory",
    businessModes: [],
    requiredPermission: "reports.read.operations",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "locationId"],
    columns: [
      { key: "ingredientName", label: "Ingredient" },
      { key: "shortageQuantity", label: "Shortage", numeric: true },
      { key: "unit", label: "Unit" },
      { key: "runStatus", label: "Run status" },
    ],
    legacyExportHref: "/api/export?type=inventory",
    generatorRoute: "/dashboard/reports/inventory_shortage_report",
    status: "available",
    financial: false,
    tags: ["inventory", "shortages"],
  },

  purchasing_report: {
    key: "purchasing_report",
    title: "Purchasing report",
    description: "Purchase orders with supplier, status and total spend.",
    category: "Purchasing",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "locationId"],
    columns: [
      { key: "createdAt", label: "Created" },
      { key: "supplierName", label: "Supplier" },
      { key: "status", label: "Status" },
      { key: "totalAmount", label: "Total", numeric: true, financial: true },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/purchasing_report",
    status: "available",
    financial: true,
    tags: ["purchasing", "supplier"],
  },

  packing_accuracy: {
    key: "packing_accuracy",
    title: "Packing accuracy",
    description:
      "Packing batches, scanned items, and exception counts to highlight packing accuracy.",
    category: "Packing",
    businessModes: [],
    requiredPermission: "reports.read.operations",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "locationId"],
    columns: [
      { key: "title", label: "Batch" },
      { key: "status", label: "Status" },
      { key: "scheduledFor", label: "Scheduled" },
      { key: "itemCount", label: "Items", numeric: true },
      { key: "exceptionCount", label: "Exceptions", numeric: true },
    ],
    legacyExportHref: "/api/export?type=packing",
    generatorRoute: "/dashboard/reports/packing_accuracy",
    status: "available",
    financial: false,
    tags: ["packing"],
  },

  delivery_report: {
    key: "delivery_report",
    title: "Delivery report",
    description: "Route stops with status, scheduled, completed and customer name.",
    category: "Delivery",
    businessModes: [],
    requiredPermission: "reports.read.operations",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "locationId", "routeId"],
    columns: [
      { key: "scheduledFor", label: "Scheduled" },
      { key: "status", label: "Status" },
      { key: "customerName", label: "Customer", pii: true },
      { key: "address", label: "Address", pii: true },
      { key: "completedAt", label: "Completed" },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/delivery_report",
    status: "available",
    financial: false,
    tags: ["delivery", "routes"],
  },

  margin_report: {
    key: "margin_report",
    title: "Margin report",
    description:
      "Latest costing snapshots per recipe with food cost percentage and target margin signals.",
    category: "Costing",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange"],
    columns: [
      { key: "recipeName", label: "Recipe" },
      { key: "foodCost", label: "Food cost", numeric: true, financial: true },
      { key: "sellingPrice", label: "Selling price", numeric: true, financial: true },
      { key: "foodCostPct", label: "Food cost %", numeric: true, financial: true },
      { key: "marginPct", label: "Margin %", numeric: true, financial: true },
    ],
    legacyExportHref: "/api/export?type=costing_snapshots",
    generatorRoute: "/dashboard/reports/margin_report",
    status: "available",
    financial: true,
    tags: ["margin", "costing"],
  },

  customer_report: {
    key: "customer_report",
    title: "Customer report",
    description: "Customer master list with order counts, lifetime value, and last order date.",
    category: "Customers",
    businessModes: [],
    requiredPermission: "reports.read.customer_pii",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "customerSegment"],
    columns: [
      { key: "name", label: "Name", pii: true },
      { key: "email", label: "Email", pii: true },
      { key: "phone", label: "Phone", pii: true },
      { key: "orderCount", label: "Orders", numeric: true },
      { key: "lifetimeValue", label: "Lifetime value", numeric: true, financial: true },
      { key: "lastOrderAt", label: "Last order" },
    ],
    legacyExportHref: "/api/export?type=customers",
    generatorRoute: "/dashboard/reports/customer_report",
    status: "available",
    financial: false,
    tags: ["customers", "crm"],
  },

  customer_retention: {
    key: "customer_retention",
    title: "Customer retention",
    description:
      "Repeat-customer ratio, lifetime value buckets, and recent churn signals for the window.",
    category: "Customers",
    businessModes: [],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange"],
    columns: [
      { key: "metric", label: "Metric" },
      { key: "value", label: "Value", numeric: true },
      { key: "context", label: "Context" },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/customer_retention",
    status: "available",
    financial: true,
    tags: ["customers", "retention"],
  },

  catering_pipeline: {
    key: "catering_pipeline",
    title: "Catering pipeline",
    description:
      "Open catering quotes by status with event date, headcount and quoted total.",
    category: "Catering",
    businessModes: ["CATERING", "RESTAURANT", "BAR", "BAKERY", "GHOST_KITCHEN"],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "status", "eventType"],
    columns: [
      { key: "title", label: "Quote" },
      { key: "status", label: "Status" },
      { key: "eventDate", label: "Event date" },
      { key: "headcount", label: "Headcount", numeric: true },
      { key: "totalAmount", label: "Total", numeric: true, financial: true },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/catering_pipeline",
    status: "available",
    financial: true,
    tags: ["catering", "sales"],
  },

  meal_plan_subscriptions: {
    key: "meal_plan_subscriptions",
    title: "Meal plan subscriptions",
    description:
      "Active meal-plan subscriptions with customer, plan, next cycle, and billing cadence.",
    category: "Meal Plans",
    businessModes: ["MEAL_PREP", "CATERING", "RESTAURANT"],
    requiredPermission: "reports.read.financial",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "status"],
    columns: [
      { key: "customerName", label: "Customer", pii: true },
      { key: "planName", label: "Plan" },
      { key: "status", label: "Status" },
      { key: "nextCycleStart", label: "Next cycle" },
      { key: "weeklyPrice", label: "Weekly price", numeric: true, financial: true },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/meal_plan_subscriptions",
    status: "available",
    financial: true,
    tags: ["meal_plans", "subscriptions"],
  },

  staff_task_completion: {
    key: "staff_task_completion",
    title: "Staff task completion",
    description: "Kitchen / operations tasks grouped by staff member with completion counts.",
    category: "Staff",
    businessModes: [],
    requiredPermission: "reports.read.operations",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange", "staffMemberId", "status"],
    columns: [
      { key: "staffName", label: "Staff member" },
      { key: "completedCount", label: "Completed", numeric: true },
      { key: "openCount", label: "Open", numeric: true },
      { key: "overdueCount", label: "Overdue", numeric: true },
    ],
    legacyExportHref: null,
    generatorRoute: "/dashboard/reports/staff_task_completion",
    status: "available",
    financial: false,
    tags: ["staff", "operations"],
  },

  audit_log_report: {
    key: "audit_log_report",
    title: "Audit log report",
    description:
      "Export-job audit trail (who exported what, when, and how many rows). Admin / superadmin only.",
    category: "Compliance / Audit",
    businessModes: [],
    requiredPermission: "reports.read.audit",
    requiredPlans: [],
    availableFormats: ["csv", "browser_print"],
    supportedFilters: ["dateRange"],
    columns: [
      { key: "createdAt", label: "When" },
      { key: "type", label: "Export type" },
      { key: "actor", label: "Actor" },
      { key: "rowCount", label: "Rows", numeric: true },
      { key: "fileName", label: "File" },
    ],
    legacyExportHref: "/api/export?type=audit_logs",
    generatorRoute: "/dashboard/reports/audit_log_report",
    status: "available",
    financial: false,
    tags: ["audit", "compliance"],
  },
};

export const REPORT_KEYS = Object.keys(REPORT_REGISTRY) as ReportKey[];

export function isReportKey(v: string | null | undefined): v is ReportKey {
  return v != null && (REPORT_KEYS as string[]).includes(v);
}

export function getReportDefinition(key: ReportKey): ReportDefinition {
  return REPORT_REGISTRY[key];
}

export function listReportDefinitions(): ReportDefinition[] {
  return REPORT_KEYS.map((k) => REPORT_REGISTRY[k]);
}
