export const PLATFORM_SUPPORT_SESSION_STARTED = "PLATFORM_SUPPORT_SESSION_STARTED" as const;
export const PLATFORM_SUPPORT_SESSION_ENDED = "PLATFORM_SUPPORT_SESSION_ENDED" as const;
export const PLATFORM_SUPPORT_SESSION_EXPIRED = "PLATFORM_SUPPORT_SESSION_EXPIRED" as const;
export const PLATFORM_SUPPORT_SESSION_REVOKED = "PLATFORM_SUPPORT_SESSION_REVOKED" as const;
