import type { BusinessType, IntegrationProvider } from "@prisma/client";

import { enrichChannelRegistryEntry } from "@/lib/channels/enrich-channel-registry-entry";
import type { ChannelDefinition, ChannelRegistryEntry } from "@/lib/channels/channel-types";

export type {
  ChannelCategory,
  ChannelCapability,
  ChannelDefinition,
  ChannelRegistryEntry,
  ChannelSetupType,
  ChannelStatusType,
  HubChannelCategory,
  LiveReadiness,
  SupportLevel,
} from "@/lib/channels/channel-types";

function allModes(): readonly BusinessType[] {
  return [
    "MEAL_PREP",
    "CATERING",
    "GHOST_KITCHEN",
    "CLOUD_KITCHEN",
    "MULTI_BRAND",
    "BAKERY",
    "RESTAURANT",
    "CAFE",
    "BAR",
    "OTHER",
  ];
}

/** Canonical channel catalog — honest about build vs placeholder. */
export const CHANNEL_DEFINITIONS: readonly ChannelDefinition[] = [
  {
    providerKey: "kitchenos-storefront",
    label: "OS Kitchen storefront",
    shortDescription: "Native public storefront and checkout on your domain.",
    longDescription:
      "Orders created here are first-class OS Kitchen orders with fulfillment, production, and packing hooks. No third-party API credentials required.",
    category: "STOREFRONT",
    statusType: "LIVE",
    supportedBusinessModes: allModes(),
    capabilities: ["orders", "products", "menus", "payments", "status_sync", "customer_sync"],
    setupType: "NATIVE",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: true,
    supportsProductSync: true,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: true,
    supportsPayments: true,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/help/getting-started",
    setupRoute: "/dashboard/storefront",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "store",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "manual-orders",
    label: "Manual orders",
    shortDescription: "Phone, counter, and internal orders created in OS Kitchen.",
    longDescription:
      "Always available. Use for walk-ins, phone orders, and adjustments. Sends to Order hub like any other order source.",
    category: "MANUAL_INTAKE",
    statusType: "LIVE",
    supportedBusinessModes: allModes(),
    capabilities: ["orders", "status_sync"],
    setupType: "MANUAL_ONLY",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: true,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/help/getting-started",
    setupRoute: "/dashboard/orders/quick",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "phone",
    mapsToIntegrationProvider: "MANUAL",
  },
  {
    providerKey: "woocommerce",
    label: "WooCommerce",
    shortDescription: "REST + webhooks for WordPress / Woo stores.",
    longDescription:
      "Consumer key/secret stored encrypted. Webhooks verified with WooCommerce signatures. Product sync and order import are buildable today — monitor webhook log for failures.",
    category: "ECOMMERCE",
    statusType: "NEEDS_CREDENTIALS",
    supportedBusinessModes: allModes(),
    capabilities: ["orders", "products", "webhooks", "customer_sync", "status_sync"],
    setupType: "WEBHOOK_PLUS_API",
    requiresCredentials: true,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: true,
    supportsOrderImport: true,
    supportsProductSync: true,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/integrations/woocommerce",
    setupRoute: "/dashboard/integrations/woocommerce",
    webhookPathHints: ["/api/webhooks/woocommerce"],
    envRequirements: ["APP_ENCRYPTION_KEY or equivalent for credential encryption"],
    requiredPlan: null,
    icon: "shoppingBag",
    mapsToIntegrationProvider: "WOOCOMMERCE",
  },
  {
    providerKey: "shopify",
    label: "Shopify",
    shortDescription: "Admin API + topic webhooks with HMAC verification.",
    longDescription:
      "Shop domain and Admin API access token encrypted at rest. Webhook secret used for HMAC — never returned to the browser after save.",
    category: "ECOMMERCE",
    statusType: "NEEDS_CREDENTIALS",
    supportedBusinessModes: allModes(),
    capabilities: ["orders", "products", "webhooks", "customer_sync", "status_sync", "inventory_sync", "markets_sync"],
    setupType: "WEBHOOK_PLUS_API",
    requiresCredentials: true,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: true,
    supportsOrderImport: true,
    supportsProductSync: true,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/integrations/shopify",
    setupRoute: "/dashboard/integrations/shopify",
    webhookPathHints: [
      "/api/webhooks/shopify/orders-create",
      "/api/webhooks/shopify/orders-updated",
      "/api/webhooks/shopify/products-update",
      "/api/webhooks/shopify/markets-create",
      "/api/webhooks/shopify/markets-update",
      "/api/webhooks/shopify/markets-delete",
      "/api/webhooks/shopify/app-uninstalled",
    ],
    envRequirements: ["SHOPIFY_APP credentials as documented"],
    requiredPlan: null,
    icon: "shoppingBag",
    mapsToIntegrationProvider: "SHOPIFY",
  },
  {
    providerKey: "uber-eats",
    label: "Uber Eats Marketplace",
    shortDescription: "Marketplace webhooks, order import, and menu sync (BETA).",
    longDescription:
      "Uber Eats BETA ships OAuth-backed order ingest, signed webhooks, menu push, and status updates. Partner-approved credentials are still required for production traffic.",
    category: "DELIVERY_MARKETPLACE",
    statusType: "PARTNER_ACCESS_REQUIRED",
    supportedBusinessModes: ["GHOST_KITCHEN", "CLOUD_KITCHEN", "RESTAURANT", "MULTI_BRAND", "OTHER"],
    capabilities: ["orders", "webhooks", "status_sync", "menu_sync"],
    setupType: "WEBHOOK_PLUS_API",
    requiresCredentials: true,
    requiresOAuth: true,
    requiresPartnerApproval: true,
    supportsWebhooks: true,
    supportsOrderImport: true,
    supportsProductSync: false,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: false,
    docsUrl: "/docs/UBER_EATS_INTEGRATION.md",
    setupRoute: "/dashboard/integrations/uber-eats",
    webhookPathHints: ["/api/webhooks/uber-eats/orders?cid=<connection-id>"],
    envRequirements: [
      "UBER_EATS_CLIENT_ID",
      "UBER_EATS_CLIENT_SECRET",
      "UBER_EATS_STORE_ID",
      "UBER_EATS_WEBHOOK_SECRET",
    ],
    requiredPlan: null,
    icon: "utensils",
    mapsToIntegrationProvider: "UBER_EATS",
  },
  {
    providerKey: "uber-direct",
    label: "Uber Direct",
    shortDescription: "Delivery dispatch quotes — separate from marketplace menus.",
    longDescription:
      "Dispatch API is gated behind Uber Direct customer provisioning. Quote routes exist as stubs until credentials are live.",
    category: "DELIVERY_DISPATCH",
    statusType: "PARTNER_ACCESS_REQUIRED",
    supportedBusinessModes: allModes(),
    capabilities: ["delivery", "status_sync"],
    setupType: "PARTNER_GATE",
    requiresCredentials: true,
    requiresOAuth: false,
    requiresPartnerApproval: true,
    supportsWebhooks: true,
    supportsOrderImport: false,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: true,
    supportsDeliveryDispatch: true,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: true,
    docsUrl: "/integrations/uber-direct",
    setupRoute: "/dashboard/integrations/uber-direct",
    webhookPathHints: ["/api/webhooks/uber-direct"],
    envRequirements: ["Uber Direct customer profile"],
    requiredPlan: null,
    icon: "bike",
    mapsToIntegrationProvider: "UBER_DIRECT",
  },
  {
    providerKey: "doordash",
    label: "DoorDash",
    shortDescription: "Marketplace webhooks, order import, menu sync, and Drive delivery (BETA).",
    longDescription:
      "DoorDash BETA ships webhook ingress with signature verification, marketplace order normalization, menu push, and Drive delivery APIs. Partner-approved credentials and API hosts are still required for production traffic.",
    category: "DELIVERY_MARKETPLACE",
    statusType: "PARTNER_ACCESS_REQUIRED",
    supportedBusinessModes: ["GHOST_KITCHEN", "RESTAURANT", "CLOUD_KITCHEN", "MULTI_BRAND"],
    capabilities: ["orders", "webhooks", "delivery", "menu_sync"],
    setupType: "WEBHOOK_PLUS_API",
    requiresCredentials: true,
    requiresOAuth: false,
    requiresPartnerApproval: true,
    supportsWebhooks: true,
    supportsOrderImport: true,
    supportsProductSync: false,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: true,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: false,
    docsUrl: "/docs/DOORDASH_INTEGRATION.md",
    setupRoute: "/dashboard/integrations/doordash",
    webhookPathHints: ["/api/webhooks/doordash/orders?cid=<connection-id>"],
    envRequirements: [
      "DOORDASH_API_KEY",
      "DOORDASH_MERCHANT_ID",
      "DOORDASH_WEBHOOK_SECRET",
    ],
    requiredPlan: null,
    icon: "truck",
    mapsToIntegrationProvider: "DOORDASH",
  },
  {
    providerKey: "grubhub",
    label: "Grubhub",
    shortDescription: "Marketplace webhooks, order import, and menu sync (BETA).",
    longDescription:
      "Grubhub BETA ships webhook ingress with signature verification, marketplace order normalization, menu push, and poll import. Partner-approved credentials are still required for production traffic.",
    category: "DELIVERY_MARKETPLACE",
    statusType: "PARTNER_ACCESS_REQUIRED",
    supportedBusinessModes: ["GHOST_KITCHEN", "RESTAURANT", "CLOUD_KITCHEN", "MULTI_BRAND"],
    capabilities: ["orders", "webhooks", "menu_sync"],
    setupType: "WEBHOOK_PLUS_API",
    requiresCredentials: true,
    requiresOAuth: false,
    requiresPartnerApproval: true,
    supportsWebhooks: true,
    supportsOrderImport: true,
    supportsProductSync: false,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: false,
    docsUrl: "/docs/GRUBHUB_INTEGRATION.md",
    setupRoute: "/dashboard/integrations/grubhub",
    webhookPathHints: ["/api/webhooks/grubhub/orders?cid=<connection-id>"],
    envRequirements: [
      "GRUBHUB_API_KEY",
      "GRUBHUB_MERCHANT_ID",
      "GRUBHUB_WEBHOOK_SECRET",
    ],
    requiredPlan: null,
    icon: "truck",
    mapsToIntegrationProvider: "GRUBHUB",
  },
  {
    providerKey: "square",
    label: "Square",
    shortDescription: "POS + catalog — OAuth and partner scopes required.",
    longDescription:
      "Placeholder roadmap channel. Square is a trademark of Block, Inc. OS Kitchen does not imply certification.",
    category: "POS",
    statusType: "COMING_SOON",
    supportedBusinessModes: ["RESTAURANT", "CAFE", "BAR", "BAKERY", "OTHER"],
    capabilities: ["orders", "products", "payments"],
    setupType: "PLACEHOLDER",
    requiresCredentials: true,
    requiresOAuth: true,
    requiresPartnerApproval: true,
    supportsWebhooks: false,
    supportsOrderImport: false,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: false,
    supportsDeliveryDispatch: false,
    supportsPayments: true,
    supportsLiveMode: false,
    isPlaceholder: true,
    docsUrl: "/contact-sales",
    setupRoute: "/dashboard/sales-channels/square/setup",
    webhookPathHints: [],
    envRequirements: ["Square application id + OAuth"],
    requiredPlan: null,
    icon: "plug",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "toast",
    label: "Toast",
    shortDescription: "Restaurant POS — partner / API access required.",
    longDescription:
      "Placeholder. Toast integration requires Toast-approved API access; OS Kitchen does not claim Toast partnership.",
    category: "POS",
    statusType: "COMING_SOON",
    supportedBusinessModes: ["RESTAURANT", "BAR", "GHOST_KITCHEN"],
    capabilities: ["orders", "menus"],
    setupType: "PLACEHOLDER",
    requiresCredentials: true,
    requiresOAuth: false,
    requiresPartnerApproval: true,
    supportsWebhooks: false,
    supportsOrderImport: false,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: false,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: true,
    docsUrl: "/contact-sales",
    setupRoute: "/dashboard/sales-channels/toast/setup",
    webhookPathHints: [],
    envRequirements: ["Toast API partnership"],
    requiredPlan: null,
    icon: "utensils",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "clover",
    label: "Clover",
    shortDescription: "POS orders — API credentials required.",
    longDescription: "Placeholder roadmap channel for Clover POS order import.",
    category: "POS",
    statusType: "COMING_SOON",
    supportedBusinessModes: allModes(),
    capabilities: ["orders", "products", "payments"],
    setupType: "PLACEHOLDER",
    requiresCredentials: true,
    requiresOAuth: true,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: false,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: false,
    supportsDeliveryDispatch: false,
    supportsPayments: true,
    supportsLiveMode: false,
    isPlaceholder: true,
    docsUrl: "/contact-sales",
    setupRoute: "/dashboard/sales-channels/clover/setup",
    webhookPathHints: [],
    envRequirements: ["Clover developer account"],
    requiredPlan: null,
    icon: "plug",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "lightspeed",
    label: "Lightspeed",
    shortDescription: "Restaurant / retail POS — API credentials required.",
    longDescription: "Placeholder roadmap channel for Lightspeed (R) POS ingestion.",
    category: "POS",
    statusType: "COMING_SOON",
    supportedBusinessModes: ["RESTAURANT", "CAFE", "BAR", "BAKERY"],
    capabilities: ["orders", "products", "inventory_sync"],
    setupType: "PLACEHOLDER",
    requiresCredentials: true,
    requiresOAuth: true,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: false,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: false,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: true,
    docsUrl: "/contact-sales",
    setupRoute: "/dashboard/sales-channels/lightspeed/setup",
    webhookPathHints: [],
    envRequirements: ["Lightspeed API credentials"],
    requiredPlan: null,
    icon: "plug",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "csv-import",
    label: "CSV import",
    shortDescription: "Structured CSV for orders, products, or customers.",
    longDescription:
      "Uses Import center and export templates. Not a live streaming channel — batch uploads with validation.",
    category: "FORMS_IMPORTS",
    statusType: "LIVE",
    supportedBusinessModes: allModes(),
    capabilities: ["orders", "products", "customer_sync"],
    setupType: "IMPORT_ONLY",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: true,
    supportsProductSync: true,
    supportsMenuSync: false,
    supportsStatusSync: false,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/help/import-export",
    setupRoute: "/dashboard/import-center",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "fileSpreadsheet",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "google-forms",
    label: "Google Forms",
    shortDescription: "Form submissions → manual or scripted import (placeholder).",
    longDescription:
      "No native Google Forms webhook is shipped. Typical pattern: Forms → Sheet → CSV → Import center, or Apps Script posting to a future authenticated endpoint.",
    category: "FORMS_IMPORTS",
    statusType: "COMING_SOON",
    supportedBusinessModes: allModes(),
    capabilities: ["orders", "customer_sync"],
    setupType: "PLACEHOLDER",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: false,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: false,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: true,
    docsUrl: "/help/import-export",
    setupRoute: "/dashboard/sales-channels/google-forms/setup",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "form",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "email-orders",
    label: "Email orders",
    shortDescription: "Manual intake from pasted email text (parser optional).",
    longDescription:
      "Operational pattern: staff pastes email content into notes or uses manual order flow. Optional AI assist only when `OPENAI_API_KEY` is configured — never implied as legal or contractual parsing.",
    category: "MANUAL_INTAKE",
    statusType: "NEEDS_SETUP",
    supportedBusinessModes: allModes(),
    capabilities: ["orders"],
    setupType: "MANUAL_ONLY",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: false,
    supportsProductSync: false,
    supportsMenuSync: false,
    supportsStatusSync: false,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: false,
    isPlaceholder: true,
    docsUrl: "/help/getting-started",
    setupRoute: "/dashboard/sales-channels/email-orders/setup",
    webhookPathHints: [],
    envRequirements: ["Optional OPENAI_API_KEY for experimental assist"],
    requiredPlan: null,
    icon: "mail",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "catering-inquiries",
    label: "Catering inquiries",
    shortDescription: "Quotes and events pipeline inside OS Kitchen.",
    longDescription:
      "Uses Catering quotes + CRM. Not a third-party feed — native workflow for B2B catering sales.",
    category: "CATERING_EVENTS",
    statusType: "LIVE",
    supportedBusinessModes: ["CATERING", "RESTAURANT", "BAR", "MEAL_PREP"],
    capabilities: ["orders", "customer_sync", "status_sync"],
    setupType: "NATIVE",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: true,
    supportsProductSync: false,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/resources/catering-production-workflow",
    setupRoute: "/dashboard/catering",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "calendar",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "bar-event-inquiries",
    label: "Bar / private event inquiries",
    shortDescription: "Event requests and packages (terminology: Event requests in bar mode).",
    longDescription:
      "Combines Catering quotes and storefront event copy. Operators remain responsible for alcohol service compliance.",
    category: "CATERING_EVENTS",
    statusType: "LIVE",
    supportedBusinessModes: ["BAR", "RESTAURANT", "CATERING"],
    capabilities: ["orders", "customer_sync"],
    setupType: "NATIVE",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: true,
    supportsProductSync: false,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: false,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/dashboard/catering",
    setupRoute: "/dashboard/catering",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "wine",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "bakery-preorder",
    label: "Bakery preorder channel",
    shortDescription: "Storefront + menus tuned for preorder windows and pickup slots.",
    longDescription:
      "Native combination of storefront checkout and weekly/preorder menus — not a separate OAuth provider.",
    category: "STOREFRONT",
    statusType: "LIVE",
    supportedBusinessModes: ["BAKERY", "CAFE"],
    capabilities: ["orders", "menus", "products", "status_sync"],
    setupType: "NATIVE",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: true,
    supportsProductSync: true,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: true,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/help/getting-started",
    setupRoute: "/dashboard/storefront",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "croissant",
    mapsToIntegrationProvider: null,
  },
  {
    providerKey: "cafe-pickup",
    label: "Café pickup channel",
    shortDescription: "Pickup-focused storefront + manual order capture.",
    longDescription: "Native: configure storefront for pickup and use manual orders for phone-ahead.",
    category: "MANUAL_INTAKE",
    statusType: "LIVE",
    supportedBusinessModes: ["CAFE"],
    capabilities: ["orders", "menus", "products"],
    setupType: "NATIVE",
    requiresCredentials: false,
    requiresOAuth: false,
    requiresPartnerApproval: false,
    supportsWebhooks: false,
    supportsOrderImport: true,
    supportsProductSync: true,
    supportsMenuSync: true,
    supportsStatusSync: true,
    supportsDeliveryDispatch: false,
    supportsPayments: true,
    supportsLiveMode: true,
    isPlaceholder: false,
    docsUrl: "/help/getting-started",
    setupRoute: "/dashboard/storefront",
    webhookPathHints: [],
    envRequirements: [],
    requiredPlan: null,
    icon: "coffee",
    mapsToIntegrationProvider: null,
  },
] as const;

export const CHANNEL_REGISTRY_ENTRIES: readonly ChannelRegistryEntry[] =
  CHANNEL_DEFINITIONS.map((d) => enrichChannelRegistryEntry(d));

export const LIVE_CAPABLE_INTEGRATION_PROVIDERS: readonly IntegrationProvider[] = CHANNEL_DEFINITIONS.flatMap((def) =>
  def.mapsToIntegrationProvider && def.supportsLiveMode && !def.isPlaceholder ? [def.mapsToIntegrationProvider] : [],
);

export function providerCountsTowardLiveReadiness(provider: IntegrationProvider): boolean {
  return LIVE_CAPABLE_INTEGRATION_PROVIDERS.includes(provider);
}

export function channelByKey(key: string): ChannelDefinition | undefined {
  return CHANNEL_DEFINITIONS.find((c) => c.providerKey === key);
}

/** Recommended subset for sidebar / onboarding hints — does not hide other channels in the hub. */
export function channelsRecommendedForBusinessType(
  businessType: BusinessType | null | undefined,
): readonly ChannelDefinition[] {
  const mode = businessType ?? "OTHER";
  const map: Partial<Record<BusinessType, readonly string[]>> = {
    MEAL_PREP: ["kitchenos-storefront", "manual-orders", "woocommerce", "shopify", "csv-import", "uber-direct"],
    RESTAURANT: ["kitchenos-storefront", "woocommerce", "shopify", "uber-eats", "doordash", "grubhub", "toast", "square", "manual-orders"],
    CAFE: ["cafe-pickup", "square", "shopify", "woocommerce", "manual-orders"],
    BAR: ["bar-event-inquiries", "square", "toast", "manual-orders", "kitchenos-storefront"],
    BAKERY: ["bakery-preorder", "woocommerce", "shopify", "csv-import", "manual-orders"],
    CATERING: ["catering-inquiries", "kitchenos-storefront", "csv-import", "manual-orders"],
    GHOST_KITCHEN: ["uber-eats", "doordash", "grubhub", "kitchenos-storefront", "shopify", "woocommerce"],
    CLOUD_KITCHEN: ["uber-eats", "grubhub", "kitchenos-storefront", "shopify", "woocommerce"],
    MULTI_BRAND: ["uber-eats", "doordash", "grubhub", "kitchenos-storefront", "shopify", "woocommerce"],
    OTHER: ["kitchenos-storefront", "manual-orders", "woocommerce", "shopify"],
  };
  const keys = map[mode] ?? map.OTHER!;
  return keys
    .map((k) => channelByKey(k))
    .filter((c): c is ChannelDefinition => Boolean(c));
}
