-- Support & issue resolution center — phase 1: enum extensions and new types only.
-- PG forbids using newly added enum labels in the same transaction (55P04); data + schema follow in 20260514190001.

ALTER TYPE "SupportTicketStatus" ADD VALUE IF NOT EXISTS 'TRIAGED';
ALTER TYPE "SupportTicketStatus" ADD VALUE IF NOT EXISTS 'WAITING_ON_SUPPORT';
ALTER TYPE "SupportTicketStatus" ADD VALUE IF NOT EXISTS 'WAITING_ON_CUSTOMER';
ALTER TYPE "SupportTicketStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "SupportTicketStatus" ADD VALUE IF NOT EXISTS 'ESCALATED';
ALTER TYPE "SupportTicketStatus" ADD VALUE IF NOT EXISTS 'DUPLICATE';
ALTER TYPE "SupportTicketStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'DATA_IMPORT';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'PRODUCT_MAPPING';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'STOREFRONT';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'PRODUCTION';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'PACKING';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'ROUTES';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'NOTIFICATIONS';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'ACCOUNT_ACCESS';
ALTER TYPE "SupportTicketCategory" ADD VALUE IF NOT EXISTS 'SECURITY';

ALTER TYPE "SupportTicketPriority" ADD VALUE IF NOT EXISTS 'CRITICAL';

CREATE TYPE "SupportTicketSeverity" AS ENUM ('LOW', 'MODERATE', 'HIGH', 'CRITICAL');
CREATE TYPE "SupportTicketSource" AS ENUM ('DASHBOARD', 'EMAIL', 'API', 'PARTNER_PORTAL', 'IMPORT', 'PUBLIC_FORM');
CREATE TYPE "SupportCommentVisibility" AS ENUM ('INTERNAL', 'CUSTOMER', 'PARTNER');
CREATE TYPE "SupportCommentAuthorType" AS ENUM ('USER', 'STAFF', 'SYSTEM');
CREATE TYPE "SupportTicketEventType" AS ENUM (
  'CREATED',
  'STATUS_CHANGED',
  'PRIORITY_CHANGED',
  'SEVERITY_CHANGED',
  'ASSIGNED',
  'COMMENT_ADDED',
  'ESCALATED',
  'RESOLVED',
  'REOPENED',
  'CLOSED',
  'SLA_WARNING',
  'ENTITY_LINKED'
);
