import Link from "next/link";

import { AiStatusBadges } from "@/components/dashboard/copilot/ai-status-badges";
import { CopilotFormErrorBanner } from "@/components/dashboard/copilot/form-error-banner";
import { CopilotInsightCard } from "@/components/dashboard/copilot/insight-card";
import { readCopilotFormError } from "@/lib/ai/copilot-form-mutation";
import { KitchenAiTools } from "@/components/dashboard/copilot/kitchen-ai-tools";
import { RefreshDeterministicButton } from "@/components/dashboard/copilot/refresh-button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { loadCopilotPageActor } from "@/lib/ux/copilot-page-access-era20";
import { prisma } from "@/lib/prisma";
import { buildDeterministicSnapshot } from "@/services/ai/deterministic-insights-service";
import {
  generateNarrative,
  getCopilotSettings,
  listActionDrafts,
  listOpenInsights,
} from "@/services/ai/copilot-service";

const NARRATIVE_COPY: Record<string, string> = {
  OK: "Generated by the configured AI provider on this request.",
  DISABLED_BY_SETTINGS: "AI narrative is disabled in copilot settings — deterministic summary only.",
  MISSING_API_KEY:
    "Set OPENAI_API_KEY on the server to enable the optional narrative. We never fake AI without a key.",
  PROVIDER_ERROR:
    "The AI provider returned an error — falling back to the deterministic summary below.",
  REDACTION_BLOCKED:
    "The outbound redaction guardrail tripped on this request — no prompt was sent.",
};

export default async function CopilotTodayPage({
  searchParams,
}: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const formError = readCopilotFormError((await searchParams) ?? {});
  const { actor, scope } = await loadCopilotPageActor();
  const { userId } = actor;

  const [settings, snapshot, profile, openInsights, drafts] = await Promise.all([
    getCopilotSettings(scope),
    buildDeterministicSnapshot(userId),
    prisma.userProfile.findUnique({
      where: { id: userId },
      select: { kitchenSettings: { select: { businessType: true } } },
    }),
    listOpenInsights(scope),
    listActionDrafts(scope, ["NEEDS_APPROVAL", "APPROVED"]),
  ]);

  const narrative = await generateNarrative(scope, {
    rangeLabel: snapshot.rangeLabel,
    bulletSummary: snapshot.bulletSummary,
    mode: profile?.kitchenSettings?.businessType ?? null,
    role: null,
  });

  const insightCards = openInsights.length > 0
    ? openInsights
    : snapshot.insights.map((s, idx) => ({
        id: `seed-${idx}`,
        severity: s.severity,
        title: s.title,
        summary: s.summary,
        recommendedAction: s.recommendedAction ?? null,
        actionRoute: s.actionRoute ?? null,
      }));

  const counts = {
    critical: snapshot.insights.filter((s) => s.severity === "CRITICAL").length,
    drafts: drafts.length,
    blockers: snapshot.insights.filter((s) => s.severity === "WARNING" || s.severity === "CRITICAL").length,
  };

  return (
    <div className="space-y-6">
      <header className="flex flex-wrap items-start justify-between gap-3">
        <div className="space-y-2">
          <h1 className="text-3xl font-semibold tracking-tight">AI Operations Copilot</h1>
          <p className="max-w-3xl text-sm text-muted-foreground">
            Safe operational insights, summaries, recommendations, and draft actions grounded in your
            OS Kitchen data.
          </p>
          <AiStatusBadges
            hasApiKey={settings.hasApiKey}
            aiNarrativeEnabled={settings.aiNarrativeEnabled}
            deterministicOnly={settings.deterministicOnly}
            redactionLevel={settings.redactionLevel}
            requireApprovalAll={settings.requireApprovalAll}
          />
        </div>
        <div className="flex flex-wrap gap-2 print:hidden">
          <RefreshDeterministicButton />
          <Link
            href="/dashboard/copilot/chat"
            className="rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground"
          >
            Ask copilot
          </Link>
        </div>
      </header>

      <CopilotFormErrorBanner message={formError} />

      <section className="grid gap-3 sm:grid-cols-3">
        <Card className="border-border/80 shadow-sm">
          <CardHeader className="pb-1">
            <CardDescription>Critical insights</CardDescription>
            <CardTitle className="text-2xl font-semibold">{counts.critical}</CardTitle>
          </CardHeader>
          <CardContent className="pt-0 text-xs text-muted-foreground">
            Deterministic, derived from your workspace.
          </CardContent>
        </Card>
        <Card className="border-border/80 shadow-sm">
          <CardHeader className="pb-1">
            <CardDescription>Open action drafts</CardDescription>
            <CardTitle className="text-2xl font-semibold">{counts.drafts}</CardTitle>
          </CardHeader>
          <CardContent className="pt-0 text-xs text-muted-foreground">
            Awaiting human approval.
          </CardContent>
        </Card>
        <Card className="border-border/80 shadow-sm">
          <CardHeader className="pb-1">
            <CardDescription>Active blockers</CardDescription>
            <CardTitle className="text-2xl font-semibold">{counts.blockers}</CardTitle>
          </CardHeader>
          <CardContent className="pt-0 text-xs text-muted-foreground">
            Warning + critical signals combined.
          </CardContent>
        </Card>
      </section>

      <KitchenAiTools />

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">What needs attention today</h2>
        {insightCards.length === 0 ? (
          <Card className="border-border/80 shadow-sm">
            <CardContent className="py-6 text-sm text-muted-foreground">
              No deterministic operational signals detected. Open the modules in the side nav to
              create orders, schedule production, or run the costing pass.
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-3">
            {insightCards.map((i) => (
              <CopilotInsightCard
                key={i.id}
                id={i.id}
                severity={i.severity}
                title={i.title}
                summary={i.summary}
                recommendedAction={i.recommendedAction}
                actionRoute={i.actionRoute}
                canResolve={!i.id.startsWith("seed-")}
              />
            ))}
          </div>
        )}
      </section>

      <Card className="border-border/80 shadow-sm">
        <CardHeader>
          <CardTitle className="text-base">Narrative summary</CardTitle>
          <CardDescription>{NARRATIVE_COPY[narrative.status]}</CardDescription>
        </CardHeader>
        <CardContent className="whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground">
          {narrative.text ?? snapshot.bulletSummary}
        </CardContent>
      </Card>

      <Card className="border-amber-300/60 bg-amber-50 dark:border-amber-700 dark:bg-amber-950/40">
        <CardHeader className="pb-1">
          <CardTitle className="text-sm">Privacy &amp; safety</CardTitle>
        </CardHeader>
        <CardContent className="pt-0 text-xs text-amber-900 dark:text-amber-100">
          Operational summaries only. Emails, phone numbers, addresses, and tokens are masked before
          any AI call. No destructive action runs without human approval.
        </CardContent>
      </Card>
    </div>
  );
}
