/**
 * Bootstrap Playwright E2E credentials into `.env.e2e.local` (gitignored).
 * Uses Supabase Admin API to set a known password on an existing or new test user.
 *
 *   npx tsx scripts/bootstrap-e2e-credentials.ts
 *   E2E_BOOTSTRAP_EMAIL=workspace.moroz@gmail.com npx tsx scripts/bootstrap-e2e-credentials.ts
 *
 * Never commit `.env.e2e.local`.
 */
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { createClient } from "@supabase/supabase-js";

import { prisma } from "@/lib/prisma";

const OUT_PATH = join(process.cwd(), ".env.e2e.local");
/** Kitchen with seeded orders/menus on linked DB (override via E2E_BOOTSTRAP_EMAIL). */
const DEFAULT_EMAIL = "workspace.moroz@gmail.com";

function loadDotenvFiles() {
  for (const name of [".env", ".env.local"]) {
    const p = join(process.cwd(), name);
    if (!existsSync(p)) continue;
    for (const line of readFileSync(p, "utf8").split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq <= 0) continue;
      const key = trimmed.slice(0, eq).trim();
      if (process.env[key]?.trim()) continue;
      let val = trimmed.slice(eq + 1).trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      process.env[key] = val;
    }
  }
}

function generatePassword(): string {
  return `KoE2e_${randomBytes(18).toString("base64url")}`;
}

async function findAuthUserId(
  admin: ReturnType<typeof createClient>,
  email: string,
): Promise<string | null> {
  const profile = await prisma.userProfile.findUnique({
    where: { email },
    select: { id: true },
  });
  if (profile?.id) return profile.id;

  for (let page = 1; page <= 10; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw error;
    const hit = data.users.find((u) => u.email?.toLowerCase() === email.toLowerCase());
    if (hit?.id) return hit.id;
    if (data.users.length < 200) break;
  }
  return null;
}

async function main() {
  loadDotenvFiles();

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL?.trim();
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY?.trim();
  if (!supabaseUrl || !serviceKey) {
    console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env / .env.local");
    process.exit(1);
  }

  const email = (process.env.E2E_BOOTSTRAP_EMAIL?.trim() || DEFAULT_EMAIL).toLowerCase();
  const password = process.env.E2E_BOOTSTRAP_PASSWORD?.trim() || generatePassword();
  const baseUrl =
    process.env.PLAYWRIGHT_BASE_URL?.trim() ||
    process.env.NEXT_PUBLIC_APP_URL?.trim() ||
    "http://127.0.0.1:3000";

  const admin = createClient(supabaseUrl, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  let userId = await findAuthUserId(admin, email);

  if (!userId) {
    const { data, error } = await admin.auth.admin.createUser({
      email,
      password,
      email_confirm: true,
      user_metadata: { full_name: "E2E Workspace", company_name: "E2E Kitchen" },
    });
    if (error) throw error;
    userId = data.user.id;
    console.log(`Created Supabase user ${email}`);
  } else {
    const { error } = await admin.auth.admin.updateUserById(userId, {
      password,
      email_confirm: true,
    });
    if (error) throw error;
    console.log(`Updated password for ${email}`);
  }

  await prisma.userProfile.upsert({
    where: { id: userId },
    create: {
      id: userId,
      email,
      fullName: "E2E Workspace",
      companyName: "E2E Kitchen",
      onboardingCompleted: true,
      onboardingStep: 99,
    },
    update: { email, onboardingCompleted: true },
  });

  const ws = await prisma.workspace.findFirst({
    where: { ownerUserId: userId },
    select: { id: true, name: true },
  });
  if (!ws) {
    await prisma.workspace.create({
      data: {
        ownerUserId: userId,
        name: "E2E Workspace",
        timezone: "UTC",
        currency: "USD",
      },
    });
    console.log("Created workspace for E2E user");
  }

  const lines = [
    "# Auto-generated by scripts/bootstrap-e2e-credentials.ts — DO NOT COMMIT",
    `E2E_LOGIN_EMAIL=${email}`,
    `E2E_LOGIN_PASSWORD=${password}`,
    `PLAYWRIGHT_BASE_URL=${baseUrl.replace(/\/$/, "")}`,
    `E2E_SEED_USER_ID=${userId}`,
    "",
  ];
  writeFileSync(OUT_PATH, lines.join("\n"), "utf8");
  console.log(`\nWrote ${OUT_PATH}`);
  console.log("Next:");
  console.log("  npm run dev   # separate terminal if local");
  console.log("  npm run test:e2e:workspace-smoke");
  console.log("\nPassword is stored only in .env.e2e.local — add that file to your password manager if needed.");

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
