import type { TemplatePreviewChange, TemplateSectionKey } from "@/lib/templates/template-types";

export type TemplateRollbackPlan = {
  /** sections that we successfully applied — used for ordered undo */
  appliedSections: TemplateSectionKey[];
  /** module pins this apply created (so rollback can un-pin them) */
  pinnedModuleKeys: string[];
  /** kitchen task ids generated by this apply */
  generatedTaskIds: string[];
  /** previous KitchenSettings.businessType (null if it was unset) */
  previousBusinessMode: string | null;
  /** whether business mode was actually changed */
  changedBusinessMode: boolean;
  /** playbook slugs we seeded for the first time (cannot delete templates, only mark inactive) */
  seededPlaybookIds: string[];
};

export function emptyRollbackPlan(): TemplateRollbackPlan {
  return {
    appliedSections: [],
    pinnedModuleKeys: [],
    generatedTaskIds: [],
    previousBusinessMode: null,
    changedBusinessMode: false,
    seededPlaybookIds: [],
  };
}

export function summariseChanges(changes: TemplatePreviewChange[]): string {
  const c = changes.reduce(
    (acc, x) => {
      acc[x.action]++;
      return acc;
    },
    { create: 0, update: 0, skip: 0, noop: 0 } as Record<string, number>,
  );
  return `create=${c.create} update=${c.update} skip=${c.skip} noop=${c.noop}`;
}
