import { describe, expect, it } from "vitest";

import {
  buildOwnerDailyBriefingContinuousImprovementLoopAction,
  CONTINUOUS_IMPROVEMENT_LOOP_BRIEFING_ACTION_PRIORITY,
} from "@/lib/briefing/owner-daily-briefing-continuous-improvement-loop-era34";
import { buildContinuousImprovementLoopUiSlice } from "@/lib/commercial/continuous-improvement-loop-ui-era22";

const sustainedOpsCompleteEnv = {
  PILOT_WEEK1_TTV_HOURS: "6",
  PILOT_WEEK1_FIRST_ORDER_ID: "ord_123",
  PILOT_WEEK1_INTEGRATION_HEALTH_REVIEWED: "1",
  PILOT_WEEK1_POS_CLOSEOUT_STATUS: "pass",
  PILOT_WEEK1_REPORTS_WEEKLY_EXPORT: "1",
  MONTH2_INVESTOR_FOUNDER_SIGNOFF: "1",
  MONTH2_GTM_GHOST_KITCHEN_LANDING_REVIEWED: "1",
  MONTH2_GTM_MEAL_PREP_LANDING_REVIEWED: "1",
  PILOT_CASE_STUDY_CUSTOMER_APPROVAL: "signed",
  SCALE_PER_CUSTOMER_GO_ISOLATION: "1",
  SCALE_SOC2_READINESS_TRACK_REVIEWED: "1",
  SCALE_SSO_PRODUCTION_STATUS: "pass",
  SCALE_RESILIENCE_DRILLS_ATTESTED: "1",
  SCALE_DATA_ROOM_INDEX_PUBLISHED: "1",
  SERIES_A_DATA_ROOM_BUNDLE_PUBLISHED: "1",
  SERIES_A_PARTNER_ONEPAGER_REVIEWED: "1",
  SERIES_A_MULTI_REGION_PLAYBOOK_DRAFTED: "1",
  SERIES_A_MARKETING_CLAIMS_STRICT_REVIEWED: "1",
  SERIES_A_CS_PLAYBOOK_REVIEWED: "1",
  MARKET_LEADER_CATEGORY_NARRATIVE_REVIEWED: "1",
  MARKET_LEADER_MOAT_DECK_REVIEWED: "1",
  MARKET_LEADER_ANALYST_KIT_PUBLISHED: "1",
  MARKET_LEADER_EXPANSION_MOTION_REVIEWED: "1",
  SUSTAINED_OPS_DAILY_CADENCE_ATTESTED: "1",
  SUSTAINED_OPS_WEEKLY_INTEGRATION_REVIEWED: "1",
  SUSTAINED_OPS_MONTHLY_METRICS_REFRESHED: "1",
  SUSTAINED_OPS_QUARTERLY_GOVERNANCE_AUDITED: "1",
};

describe("owner-daily-briefing-continuous-improvement-loop-era34", () => {
  it("builds ranked action with priority 9 when improvement loop active", () => {
    const slice = buildContinuousImprovementLoopUiSlice({
      goNoGoSummary: {
        version: "era17-pilot-gono-go-v1",
        runAt: new Date().toISOString(),
        decision: "GO",
        blockers: [],
        warnings: [],
        customerExecutionStatus: "recorded",
        customerName: "Acme",
        loiSignedDate: "2026-06-01",
        prospectExecutionStatus: "none",
        prospectName: null,
        icpQualification: { qualified: true, missingCriteria: [], disqualifiers: [] },
        evidenceGates: [],
        evaluatorInput: {
          tier0Pass: true,
          tier1Pass: true,
          tier2Pass: true,
          tier3Pass: true,
          roleChecklistsComplete: true,
          forbiddenClaimsInContract: false,
          icpQualified: true,
          stagingUrl: "https://x.example.com",
          commitSha: "abc",
        },
      },
      p0Staging: {
        version: "era17-p0-staging-proof-unblock-v1",
        runAt: new Date().toISOString(),
        commitSha: "abc",
        overall: "PASSED",
        p0ProofStatus: "proof_passed",
        defaultProofStatus: "awaiting_ops_credentials",
        allMissingEnvVars: [],
        children: {
          ssoIdpStaging: {
            smokeScript: "x",
            artifactPath: "x",
            overall: "PASSED",
            proofStatus: "proof_passed",
            missingEnvVars: [],
          },
          stagingWorkflowsFirstGreen: {
            smokeScript: "x",
            artifactPath: "x",
            overall: "PASSED",
            proofStatus: "proof_passed",
            missingEnvVars: [],
          },
          channelLive: {
            smokeScript: "smoke:woo-shopify-live",
            artifactPath: "x",
            overall: "PASSED",
            proofStatus: "proof_passed",
            missingEnvVars: [],
          },
        },
      },
      tier2Summary: {
        version: "era20-tier2-staging-golden-path-v1",
        runAt: new Date().toISOString(),
        commitSha: "abc",
        overall: "PASSED",
        tier2ProofStatus: "proof_passed",
        p0ProofStatus: "proof_passed",
        steps: [],
        missingManualEnvVars: [],
        playbookDoc: "docs/x.md",
      },
      metricsBaseline: {
        version: "era17-pilot-metrics-baseline-v1",
        policyId: "era17-pilot-metrics-baseline-v1",
        runAt: new Date().toISOString(),
        overall: "PASSED",
        baselineProofStatus: "proof_captured",
        pilotWeek: 8,
        customerRef: "Acme",
        capturedAt: new Date().toISOString(),
        metrics: ["orders_per_day"].map((id) => ({
          id,
          label: id,
          status: "captured" as const,
          value: 1,
          unit: "n/a",
        })),
        capturedCount: 1,
        missingCount: 0,
      },
      caseStudyDraft: {
        version: "era17-pilot-case-study-draft-v1",
        runAt: new Date().toISOString(),
        commitSha: "abc",
        overall: "PASSED",
        caseStudyProofStatus: "internal_draft_ready",
        publishProofStatus: "proof_ready_for_publish",
        pilotMetricsArtifactLoaded: true,
        pilotMetricsOverall: "PASSED",
        customerApprovalStatus: "signed",
        certPassed: true,
      },
      investorOnepager: {
        version: "era17-investor-narrative-onepager-v2-v1",
        runAt: new Date().toISOString(),
        commitSha: "abc",
        overall: "PASSED",
        narrativeProofStatus: "proof_ready_with_metrics",
        pilotMetricsArtifactLoaded: true,
        pilotMetricsOverall: "PASSED",
        pilotMetricsBaselineProofStatus: "proof_captured",
        pilotMetricsCapturedCount: 6,
        certPassed: true,
      },
      rollbackDrill: {
        version: "era17-pilot-rollback-drill-v1",
        policyId: "era17-pilot-rollback-drill-v1",
        runAt: new Date().toISOString(),
        drillMode: "tabletop",
        rollbackProofStatus: "proof_passed",
        stagingUrl: null,
        operatorEmail: null,
        rollbackReason: null,
        commitSha: "abc",
        retrospective: { outcome: null, lessons: null, recorded: false },
        steps: [{ order: 1, action: "isolate", owner: "ops", status: "PASSED" as const, reason: null }],
        passedStepCount: 1,
        totalSteps: 1,
      },
      competitorMatrix: {
        version: "era17-competitor-feature-gap-matrix-v1",
        runAt: new Date().toISOString(),
        commitSha: "abc",
        overall: "PASSED",
        matrixProofStatus: "evidence_aligned_era17",
        certPassed: true,
        requiredCompetitorCount: 3,
      },
      env: {
        ...sustainedOpsCompleteEnv,
        CONTINUOUS_IMPROVEMENT_LOOP_PURE_MODE_ATTESTED: "1",
      },
    });
    const action = buildOwnerDailyBriefingContinuousImprovementLoopAction(slice);
    expect(action?.id).toBe("continuous-improvement-loop");
    expect(action?.priority).toBe(CONTINUOUS_IMPROVEMENT_LOOP_BRIEFING_ACTION_PRIORITY);
  });
});
